### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1010]
```
{"level":60,"time":1630392167774,"name":"query","err":{"type":"AssertionError","message":"The expression evaluated to a falsy value:\n\n  assert(!this.currentMessage.request)\n","stack":"AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert(!this.currentMessage.request)\n\n    at Parser.destroy (/usr/src/app/node_modules/undici/lib/client.js:647:5)\n    at Socket.onSocketClose (/usr/src/app/node_modules/undici/lib/client.js:1064:17)\n    at Socket.emit (node:events:394:28)\n    at TCP.<anonymous> (node:net:672:12)","generatedMessage":true,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="},"msg":"error caused exit"}
```

  "undici": "4.4.5"

**Comment by ronag** [comment]
happens with pipelining

**Comment by mcollina** [comment]
Did you find out why?

**Comment by ronag** [comment]
No, it's just putting it here for now so I don't forget. Don't have time to investigate atm.
