### ISSUE TITLE
export exception when packed with Nexe

### ISSUE THREAD

**Issue by Taelyn** [nodejs/undici#1087]
## Bug Description

TypeError: Cannot destructure property 'exports' of 'undefined' as it is undefined.
    at new Parser (xxxx\node_modules\undici\lib\client.js:494:34)
    at connect (xxxx\node_modules\undici\lib\client.js:1175:23)

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (xxxx\node_modules\undici\lib\client.js:1280:29)
    at resume (xxxx\node_modules\undici\lib\client.js:1244:3)
    at connect (xxxx\node_modules\undici\lib\client.js:1229:3)

## Reproducible By

When code and modules are packed with Nexe since a while i get this error

## Expected Behavior

Didnt happen before, started to happen since october

## Environment

Node v17
Windows 64 bit

**Comment by mcollina** [comment]
I have a feeling this was a side effect of https://github.com/nodejs/undici/pull/1077.

@Taelyn could you include instructions to reproduce the problem? A script would be perfect.

**Comment by Taelyn** [comment]
Hi,

narrowed it down that v4.8.0 is the last one it worked. on first iam getting this error on 4.8.1

Error: ENOENT: no such file or directory, open 'xxxx\node_modules\undici\lib\llhttp\llhttp.wasm'

And after the pull you mentioned iam getting the error above

Its a DiscordBot here is my command:
```
const { request } = require('undici');

module.exports = {
    name: 'cat',
    description: 'Shows a random picture of a cat.',
    triggers: [],
    arguments: [],
    enabled: true,
    memberPermissions: [],
    memberVoicePermissions: [],
    clientPermissions: ['SEND_MESSAGES', 'EMBED_LINKS'],
    schedulable: true,
    unsafe: false,
    nsfw: false,
    cooldown: 0,
    ratelimit: 1,
    ownerBot: false,
    usage: ['cat'],
    example: [],

    async exec(client, message, args) {
        try {
            const { body } = await request('https://api.thecatapi.com/v1/images/search');
            const response = await body.json();

            await message.channel.send({
                embeds:
                    [{
                        image:
                        {
                            url: response[0].url
                        }
                    }]
            }).catch(e => {
                client.log.error(e.stack);
            });
        } catch (e) {
            client.log.error(e.stack);
        }
    }
};
```
npm script i use to build with nexe to convert my code to a .exe
```
  "scripts": {
    "build": "nexe -n \"TestBot\" -r \"node_modules/**/*\" -r \"package.json\" -r \"app.js\" -r \"events/**/*\" -r \"handlers/**/*\" -r \"commands/**/*\" -b --verbose"
  },
```

**Comment by mcollina** [comment]
It seems
nexe is not bundling the wasm file .

**Comment by Taelyn** [comment]
Is this a nexe problem? as on v4.8.0 it all works fine?
Any way it can be fixed? For now i will stay on 4.8.0

**Comment by mcollina** [comment]
I think it could be fixed. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Taelyn** [comment]
ill try :)

**Comment by shellscape** [comment]
I'm getting the original error as described, including the exact stack trace, after attempting to run a bundle that was created with esbuild, on v4.12.1 of undici. I'll attempt to use the latest version and will report back on if the same thing is happening.

**Comment by mcollina** [comment]
Thanks!

**Comment by aguidrevitch** [comment]
I hit the issue when I create systemd service and set memory limit as LimitAS=6G. node 18

```
TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:6406:34)
    at node:internal/deps/undici/undici:6727:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
  cause: TypeError: Cannot destructure property 'exports' of 'undefined' as it is undefined.
      at new Parser (node:internal/deps/undici/undici:3616:46)
      at connect (node:internal/deps/undici/undici:4099:27)
}
node:internal/deps/undici/undici:4185
            if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                                ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (node:internal/deps/undici/undici:4185:33)
    at resume (node:internal/deps/undici/undici:4155:7)
    at connect (node:internal/deps/undici/undici:4144:7)
```

Without LimitAS
```
# cat /proc/9614/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             31734                31734                processes 
Max open files            524288               524288               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       31734                31734                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us   
```

With LimitAS
```# cat /proc/9519/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             31734                31734                processes 
Max open files            524288               524288               files     
Max locked memory         65536                65536                bytes     
Max address space         6442450944           6442450944           bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       31734                31734                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us    
```
If I remove LimitAS - everything works just fine. I also run service as www-data, if that matters.
