### ISSUE TITLE
Support `createObjectURL` based `blob:` URLs in node 16+

### ISSUE THREAD

**Issue by willstott101** [nodejs/undici#1164]
Node's experimental [URL.createObjectUrl](https://nodejs.org/api/url.html#urlcreateobjecturlblob) creates URLs to blob data that look something like this: `blob:nodedata:ee7f0009-a19f-47f3-935f-08fa7ca35adc`

In the browser environment `fetch` and friends will accept `blob:` URLs to allow applications to pass URL references to large Blobs of data without needing to pull them into data URIs.

For me this is especially useful when working with libraries like THREE.js which make heavy use of fetch APIs - which then need to be monkey-patched in NodeJS

## Logs & Screenshots

What I'm seeing atm:

```
(node:18940) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18940) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
Promise { <pending> }
/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:176
        Object.assign(new TypeError('fetch failed'), { cause: response.error })
                      ^

TypeError: fetch failed
    at Object.processResponse (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:176:23)
    at fetchFinale (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:737:17)
    at Fetch.mainFetch (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:712:5) {
  cause: Error: URL scheme must be a HTTP(S) scheme
      at makeNetworkError (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/response.js:364:11)
      at /home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:560:16
      at Fetch.mainFetch (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:583:7)
      at Fetch.fetching (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:452:20)
      at Agent.fetch (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/lib/fetch/index.js:195:6)
      at fetch (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/undici/index.js:102:22)
      at FileLoader.load (/home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/three/build/three.js:28384:4)
      at GLTFLoader.load (file:///home/wstott/repos/tritium/libs/typescript/tritium_3d_view/node_modules/three/examples/jsm/loaders/GLTFLoader.js:190:10)
      at file:///home/wstott/repos/tritium/libs/typescript/tritium_3d_view/tools/gltf2sdf.ts:26:14
      at new Promise (<anonymous>)
}

```

I'm assuming by  `URL scheme must be a HTTP(S) scheme` blob schemes are simply not implemented, as opposed to there being a bug.

## Environment

Ubuntu 18.04 LTS, Node v17.3.1, Undici 4.12.1

**Comment by KhafraDev** [comment]
I've actually had a PR in a half finished state adding support for `blob:` and `about:` (easiest to add) uris that just isn't good because the spec gives no indication as to how it should be triggered.
