### ISSUE TITLE
Question: What circumstances do these errors occur?

### ISSUE THREAD

**Issue by cjh980402** [nodejs/undici#1228]
```
ConnectTimeoutError: Connect Timeout Error
    at Timeout.onConnectTimeout [as _onTimeout] (/home/ubuntu/my-nodejs/node_modules/undici/lib/core/connect.js:106:24)
    at listOnTimeout (node:internal/timers:559:11)
    at processTimers (node:internal/timers:500:7)
```
I got this error sometimes, when I used `undici.request`.
What circumstances do these errors occur?
Also, how can I prevent this error?

**Comment by cjh980402** [comment]
I fount some issue about my server.
Thank you for good http module.

**Comment by rathax** [comment]
@cjh980402 what was the issue? currently facing the same error message.

**Comment by cjh980402** [comment]
I made too many request or my server was overloaded.

**Comment by hang-wang-sys** [comment]
> I made too many request or my server was overloaded.
Has your problem been solved? I also encounter the same problem. I don't know whether it is the problem of socket5 configuration and how to configure socket5 for access

ConnectTimeoutError: Connect Timeout Error
    at Timeout.onConnectTimeout [as _onTimeout] (C:\Users\a\Downloads\discord-giveaways-bot-master\discord-giveaways-bot-master\node_modules\undici\lib\core\connect.js:108:24)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}
