### ISSUE TITLE
`fetch` fails on `ByteString` header with non-ASCII chars

### ISSUE THREAD

**Issue by AlttiRi** [nodejs/undici#1317]
`fetch` fails on `ByteString` header if the header contains char codes `128` and over.

[The code:](https://gist.github.com/AlttiRi/9c1364719bc78466a39ac8c1acc0eb45)

<details>
<summary>server.js</summary>

```js
import http from "http";

const host = "localhost";
const port = 8000;
const server = http.createServer(requestListener);
server.listen(port, host, () => {
    console.log(`Server is running on http://${host}:${port}`);
});

const names = [
    `rock&roll.png`,
    `rock'n'roll.png`,
    `image — copy (1).png`,
    `_圖片_🖼_image_.png`,
    `100 % loading&perf.png`,
];

const CD1 = str2BStr(`inline; filename=${names[0]}`);
const CD2 = str2BStr(`inline; filename="${names[1]}"`);
const CD3 = str2BStr(`inline; filename="${names[2]}"; filename*=UTF-8''${encodeURIComponent(names[2])}`);
const CD4 = str2BStr(`inline; filename="${names[3]}"; filename*=UTF-8''${encodeURIComponent(names[3])}`);
const CD5 = str2BStr(`inline; filename="${names[4]}"; filename*=UTF-8''${encodeURIComponent(names[4])}`);


function requestListener(req, res) {
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.setHeader("Content-Disposition-1", CD1);
    res.setHeader("Content-Disposition-2", CD2);
    res.setHeader("Content-Disposition-3", CD3);
    res.setHeader("Content-Disposition-4", CD4);
    res.setHeader("Content-Disposition-5", CD5);
    res.writeHead(200);
    res.end(names.map(name => `<li>${name}</li>`).join(""));
}


// --- Util ---
function str2BStr(string) {
    return arrayBufferToBinaryString(new TextEncoder().encode(string));
}
function bSrt2Str(bString) {
    return new TextDecoder().decode(binaryStringToArrayBuffer(bString));
}
function arrayBufferToBinaryString(arrayBuffer) {
    return arrayBuffer.reduce((accumulator, byte) => accumulator + String.fromCharCode(byte), "");
}
function binaryStringToArrayBuffer(binaryString) {
    const u8Array = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        u8Array[i] = binaryString.charCodeAt(i);
    }
    return u8Array;
}

```
</details>

<details>
<summary>client.js</summary>

```js
import {fetch} from "undici";
// import fetch from "node-fetch";

let result = [...(await fetch("http://localhost:8000/", {method: "head"})).headers.entries()]
    .filter(([k, v]) => k.startsWith("content-disposition"))
    .map(([k, v]) => v)
console.log(result);
console.log(result.map(v => v.length));


// import {contentDispositionFilename} from "./util.js";
// console.log(result.map(v => contentDispositionFilename(v)));
```
</details>

<details>
<summary>util.js</summary>

```js
export {contentDispositionFilename};

/* Using:
const cd = response.headers.get("content-disposition");
const name = contentDispositionFilename(cd);
 */
// RFC 5987:
// [1] inline; filename="file.jpg"; filename*=UTF-8''file.jpg
// Quoted:
// [2] inline; filename="file.jpg"
// Without quotes:
// [3] attachment; filename=file.jpg
//
// `filename=` in rare cases may be also encoded as URIComponent
function contentDispositionFilename(headerByteString, decode = false) {
    if (!headerByteString) {
        return;
    }

    const headerString = byteStringToString(headerByteString);
    if (headerString !== headerByteString) {
        console.log("contentDispositionHeaderByteString:", headerByteString);
        console.log("contentDispositionHeaderString:",     headerString);
    }

    let result;
    const encodedFilename = headerString.match(/(?<=filename\*=UTF-8'')[^;]+(?=;?$)/)?.[0]; // [1]
    if (encodedFilename) {
        result = decodeURIComponent(encodedFilename);
    } else {
        const filename = headerString.match(/(?<=filename=").+(?="$)/)?.[0] // [2]
                      || headerString.match(/(?<=filename=).+$/)[0];        // [3]

        if (decode) {
            result = decodeURIComponent(filename);
        } else {
            result = filename;
        }
    }
    console.log("contentDispositionFilename:", result);

    return result;
}
function byteStringToString(byteString) {
    const chars = [...byteString];
    const isBinaryString = chars.every(ch => ch.charCodeAt(0) < 256);
    if (isBinaryString) {
        console.log("isBinaryString", isBinaryString);

        // It's optional, just to skip `TextDecoder.decode`
        const isASCII = chars.every(ch => ch.charCodeAt(0) < 128);
        if (isASCII) {
            console.log("isASCII", isBinaryString);
            return byteString;
        }

        const bytes = new Uint8Array(chars.map(ch => ch.charCodeAt(0)));
        return new TextDecoder().decode(bytes);
    }
    return byteString;
}

```
</details>

### Result

```js
...\node_modules\undici\lib\fetch\index.js:186
        Object.assign(new TypeError('fetch failed'), { cause: response.error })
                      ^

TypeError: fetch failed
    at Object.processResponse (...\node_modules\undici\lib\fetch\index.js:186:23)
    at Fetch.fetchFinale (...\node_modules\undici\lib\fetch\index.js:940:17)
    at Fetch.mainFetch (...\node_modules\undici\lib\fetch\index.js:747:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition-3"]
      at normalizeAndValidateHeaderValue (...\node_modules\undici\lib\fetch\headers.js:48:3)
      at HeadersList.append (...\node_modules\undici\lib\fetch\headers.js:98:29)
      at Headers.append (...\node_modules\undici\lib\fetch\headers.js:220:31)
      at Object.onHeaders (...\node_modules\undici\lib\fetch\index.js:1844:21)
      at Request.onHeaders (...\node_modules\undici\lib\core\request.js:176:27)
      at Parser.onHeadersComplete (...\node_modules\undici\lib\client.js:859:23)
      at wasm_on_headers_complete (...\node_modules\undici\lib\client.js:458:30)
      at wasm://wasm/0002afd2:wasm-function[11]:0x427
      at wasm://wasm/0002afd2:wasm-function[44]:0x8ad
      at wasm://wasm/0002afd2:wasm-function[56]:0x5c62 {
    code: 'ERR_INVALID_CHAR'
  }
}
```

### The expected result

Deno:
![image](https://user-images.githubusercontent.com/16310547/161149548-0c61d40f-35b7-457f-80bb-f6fd4e37741b.png)

Browser console:
![image](https://user-images.githubusercontent.com/16310547/161151859-eb5aee74-7f03-4968-8642-a7fb017c7a34.png)

Browser:
![image](https://user-images.githubusercontent.com/16310547/161151943-2dce9946-0b0a-4acb-8d67-55fc09529662.png)

Deno, with 2 last lines uncommented:
![image](https://user-images.githubusercontent.com/16310547/161149638-6807d3b1-beb4-461a-87b2-391811b090cb.png)

```
Node.js v17.5.0
undici v4.16.0
```

---

BTW, HTTP headers are `ByteString` (BinaryString).

https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary
https://webidl.spec.whatwg.org/#idl-ByteString

Hm... someone have deleted the article about `ByteString`:
https://web.archive.org/web/20210608032047/https://developer.mozilla.org/en-US/docs/Web/API/ByteString
and replaced `ByteString` with `String`:
https://web.archive.org/web/20210731105134/https://developer.mozilla.org/en-US/docs/Web/API/Headers/get
That's **not** OK.

**Comment by AlttiRi** [comment]
https://github.com/nodejs/undici/blob/a211b186a9ff4c2993de2cb0f77b5650edd1628d/lib/fetch/index.js#L1950-L1951

```js
            const key = headersList[n + 0].toString("binary")
            const val = headersList[n + 1].toString("binary")
```

**Comment by ronag** [comment]
@Ethan-Arrowood

**Comment by Ethan-Arrowood** [comment]
@AlttiRi would you like to send your fix as a PR?

**Comment by AlttiRi** [comment]
The additional note about `undici.request`, but not about `undici.fetch`:

`undici.request` returns headers as a `String` — it automatically converts UTF-8 bytes to a `String`. 
For a library that is not going to be "`fetch` compatible" it's probably OK.
However, I think you should at least document this detail.

Setting header with non-`Latin 1` encoding in `undici.request` is allowed (no errors are thrown), but it produces a wrong result (I can't parse on the server the header received from `undici.request` correctly), I need to manually convert the header string to `ByteString`.

It's looks strange.
It (`undici.request`) automatically converts utf-8 bytes to String on reading, but it does not convert a String to utf-8 bytes on header setting.

**Comment by AlttiRi** [comment]
Also you can take a look at this issue:
https://github.com/nodejs/node/issues/42579
There I wrote in more details about the `ByteString` header representation.

**Comment by AlttiRi** [comment]
Not for this issue, definitely.

This issue is about that `undici.fetch` produces the different results, or does not work with at all with real URLs in comparison with browsers `fetch`, `node-fetch`, deno's `fetch`.

**Comment by mcollina** [comment]
What does UPD mean?

Given you are not interested in fixing this, could we close the issue then?

**Comment by AlttiRi** [comment]
> What does UPD mean?

"Update". (I added additional information by editing)

> Given you are not interested in fixing this

I'm very interested in fixing this. This bug is critical.

---

I only removed my fork because my pull request has disappeared here from the list.

Well, anyway it was just 2 lines of changes, so anyone can recreate it instead without any problem.

I'm not interesting in a contribution, I'm only interested in this bug fixing.

**Comment by AlttiRi** [comment]
Oh, was it fixed?

Finally, I can use this library.

BTW, a real life _(with no authentication needed)_ URL for tests:
https://web.archive.org/web/1/https://download1084.mediafire.com/z7j89kwbqrzg/gphbkhjqqx8aesq/✅⏳🔥💧.txt

**Comment by AlttiRi** [comment]
5.10.0 works as expected.

```js
import {fetch} from "undici";


// Use this persistent Web Archive URL,
// or take the direct URL for your IP here: 
// https://www.mediafire.com/file/gphbkhjqqx8aesq/%E2%9C%85%E2%8F%B3%F0%9F%94%A5%F0%9F%92%A7.txt
// from the "DOWNLOAD (14B)" button element
const url = "https://web.archive.org/web/1/https://download1084.mediafire.com/z7j89kwbqrzg/gphbkhjqqx8aesq/✅⏳🔥💧.txt";

const resp = await fetch(url);

if (!resp.ok) { // status === 503 if "Internet Archive services are temporarily offline."
    throw "status: " + resp.status;
}

const cdHeader = Buffer.from(resp.headers.get("content-disposition"), "latin1").toString();
const {filename} = cdHeader.match(/filename="(?<filename>.+)"/)?.groups;
console.log(filename);

console.log(filename === "✅⏳🔥💧.txt");      // true
console.log(await resp.text() === "✅⏳🔥💧"); // true
```
