### ISSUE TITLE
MockAgent: request not intercepted when `method`s are lowercase

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1320]
## Reproducible By

```js
import { fetch, MockAgent, setGlobalDispatcher } from 'undici';

const mockAgent = new MockAgent();
mockAgent.disableNetConnect();
setGlobalDispatcher(mockAgent);

const mockPool = mockAgent.get('http://localhost:3000');

mockPool.intercept({
	path: '/test',
	method: 'patch'
}).reply(200, 'Hello!');

const r = await fetch('http://localhost:3000/test', {
	method: 'PATCH'
});

console.log(await r.text());
```

## Expected Behavior

It should work with `PATCH` and `patch` methods (this works for GET, POST, etc.).

## Logs & Screenshots

```
\node_modules\undici\lib\fetch\index.js:183
        Object.assign(new TypeError('fetch failed'), { cause: response.error })
                      ^

TypeError: fetch failed
    at Object.processResponse (\node_modules\undici\lib\fetch\index.js:183:23)
    at Fetch.fetchFinale (\node_modules\undici\lib\fetch\index.js:937:17)
    at Fetch.mainFetch (\node_modules\undici\lib\fetch\index.js:744:17) {
  cause: MockNotMatchedError: Mock dispatch not matched for method 'PATCH': subsequent request to origin http://localhost:3000 was not allowed (net.connect disabled)
      at MockPool.dispatch (\node_modules\undici\lib\mock\mock-utils.js:206:19)
      at Agent.dispatch (\node_modules\undici\lib\agent.js:142:25)
      at MockAgent.dispatch (\node_modules\undici\lib\mock\mock-agent.js:54:25)
      at \node_modules\undici\lib\fetch\index.js:1809:24
      at new Promise (<anonymous>)
      at Fetch.httpNetworkFetch (\node_modules\undici\lib\fetch\index.js:1550:10)
      at Fetch.httpNetworkOrCacheFetch (\node_modules\undici\lib\fetch\index.js:1409:52)
      at Fetch.httpFetch (\node_modules\undici\lib\fetch\index.js:995:63)
      at Fetch.schemeFetch (\node_modules\undici\lib\fetch\index.js:892:10)
      at \node_modules\undici\lib\fetch\index.js:552:12 {
    code: 'UND_MOCK_ERR_MOCK_NOT_MATCHED'
  }
}
```

## Environment

windows 10 node v17.7.1

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
