### ISSUE TITLE
[I am sorry about this] Jest bug when using `MockScope.delay`

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1327]
## Bug Description

I want to preface that using Jest was not my choice.

## Reproducible By

```js
import { MockAgent, setGlobalDispatcher, request } from 'undici'

const mockAgent = new MockAgent();
mockAgent.disableNetConnect();
setGlobalDispatcher(mockAgent);

const mockPool = mockAgent.get('http://localhost:3333');

mockPool.intercept({
	path: '/jest-bugs',
	method: 'GET'
}).reply(200, 'Hello').delay(100).times(2);

test('I wish this codebase used tap', async () => {
	const ac = new AbortController();
	setTimeout(() => ac.abort(), 5);
	const promise = request('http://localhost:3333/jest-bugs', {
		signal: ac.signal
	});

	await expect(promise).rejects.toThrowError('Request aborted');
}, 1000);
```

## Logs & Screenshots

```
 PASS  __tests__/Jest.test.ts
  √ I wish this codebase used tap (16 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 | 
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.187 s, estimated 2 s
Ran all test suites matching /__tests__\\Jest.test.ts/i.
node:async_hooks:202
        ReflectApply(fn, thisArg, args);
        ^

TypeError: Function.prototype.apply was called on null, which is a object and not a function
    at RequestHandler.runInAsyncScope (node:async_hooks:202:9)
    at RequestHandler.onHeaders (\node_modules\undici\lib\api\api-request.js:91:10)
    at handleReply (\node_modules\undici\lib\mock\mock-utils.js:200:13)
    at Timeout._onTimeout (\node_modules\undici\lib\mock\mock-utils.js:189:7)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Node.js v17.8.0
```

## Environment

Windows 10 Nodejs v17.8.0

### Additional context

Even though the test passes, the CI still exits with exit code 1 and the workflow fails 😢

**Comment by KhafraDev** [comment]
The issue in async_hooks is due to `callback` being null from https://github.com/nodejs/undici/blob/17e6a0f464b32ef59c27b1b8fe9d37c71fa16c4a/lib/api/api-connect.js#L48

I have no idea how to debug this.

**Comment by mcollina** [comment]
I would literally tempest the file with console.log and debugger; statements to identify what happens with this.callback and why it's null. By the look of it we need an if-block similar to the one in onError.

**Comment by KhafraDev** [comment]
Not that bad to debug really... much easier than I expected.

Somewhere an error occurs, triggering the `onError` callback;
https://github.com/nodejs/undici/blob/f5d9a94e8771708a2d3654e412cb82404bf7cf4f/lib/api/api-request.js#L116
where err is
```
RequestAbortedError [AbortError]: Request aborted
          at abort (\undici\lib\api\abort-signal.js:12:18)
          at AbortSignal.self.<computed> (\undici\lib\api\abort-signal.js:32:5)
          at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
          at AbortSignal.dispatchEvent (node:internal/event_target:585:26)
          at abortSignal (node:internal/abort_controller:291:10)
          at AbortController.abort (node:internal/abort_controller:322:5)
          at Timeout._onTimeout (\undici\test\jest\jest.test.js:17:22)
          at listOnTimeout (node:internal/timers:559:17)
          at processTimers (node:internal/timers:502:7) {
        code: 'UND_ERR_ABORTED'
      }

      at RequestHandler.onError (lib/api/api-request.js:119:13)
```
The stack trace itself doesn't mean much, it just shows that the request was successfully aborted (yay!).

Since `callback` exists, the statement runs, and sets the callback to null here;
https://github.com/nodejs/undici/blob/f5d9a94e8771708a2d3654e412cb82404bf7cf4f/lib/api/api-request.js#L123

If the fix is just to add an `if (callback !== null) { ... }` then I am glad to make a PR, but I'm not really familiar with this section of the code and what [in]correct behavior looks like.

**Comment by mcollina** [comment]
go for it!

**Comment by BobNobrain** [comment]
I have the same error with `stream` instead of `request`. Should the same fix be added to [`api-stream.js`](https://github.com/nodejs/undici/blob/main/lib/api/api-stream.js#L107)?

Repro:

```js
const {MockAgent, stream} = require('undici');
const {Writable} = require('stream');

async function main() {
    const mockAgent = new MockAgent();

    mockAgent.disableNetConnect();
    mockAgent
        .get('http://localhost')
        .intercept({
            path: '/'
        })
        .reply(200, 'ok')
        .delay(100);

    const parts = [];
    const ac = new AbortController();

    setTimeout(() => ac.abort('nevermind'), 50);

    try {
        await stream('http://localhost/', {
            opaque: {parts},
            signal: ac.signal,
            dispatcher: mockAgent
        }, ({opaque: {parts}}) => {
            return new Writable({
                write(chunk, _encoding, callback) {
                    parts.push(chunk);
                    callback();
                }
            });
        });

        console.log(Buffer.concat(parts).toString('utf-8'));
    } catch (error) {
        console.error('aborted', error);
    }
}

main().catch((e) => {
    console.error('fatal', e);
    process.exit(3);
});
```

Outputs:

```
$ node repro.js
aborted RequestAbortedError [AbortError]: Request aborted
    at abort (project/node_modules/undici/lib/api/abort-signal.js:11:18)
    at AbortSignal.self.<computed> (project/node_modules/undici/lib/api/abort-signal.js:30:5)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
    at abortSignal (node:internal/abort_controller:292:10)
    at AbortController.abort (node:internal/abort_controller:323:5)
    at Timeout._onTimeout (project/repro.js:19:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_ABORTED'
}
node:async_hooks:203
        ReflectApply(fn, thisArg, args);
        ^

TypeError: Function.prototype.apply was called on null, which is a object and not a function
    at StreamHandler.runInAsyncScope (node:async_hooks:203:9)
    at StreamHandler.onHeaders (project/node_modules/undici/lib/api/api-stream.js:107:18)
    at handleReply (project/node_modules/undici/lib/mock/mock-utils.js:278:13)
    at Timeout._onTimeout (project/node_modules/undici/lib/mock/mock-utils.js:247:7)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
$ echo $?
1
```

**Comment by KhafraDev** [comment]
could you make a separate issue?
