### ISSUE TITLE
Error: connect ECONNREFUSED ::1:19001

### ISSUE THREAD

**Issue by masx200** [nodejs/undici#1413]
## Bug Description

```

(node:1800) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1800) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
node:internal/process/esm_loader:91
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: connect ECONNREFUSED ::1:19001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 19001
}

```
```ts
import { ProxyAgent, request } from "undici";

const proxyAgent = new ProxyAgent("http://localhost:19001");

const {
    statusCode,
    body,
    headers,
} = await request("http://www.baidu.com", { dispatcher: proxyAgent });

console.log("response received", statusCode); // response received 200
console.log(headers);
for await (const data of body) {
    console.log("data", data.toString("utf8")); // data foo
}

```
## Reproducible By

```
 npx esmo "C:\Documents\测试\test\test.ts"
```
## Expected Behavior

```
(node:2384) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2384) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
response received 307
{
  location: 'https://www.baidu.com/',
  vary: 'Accept-Encoding',
  'content-length': '0',
  date: 'Thu, 05 May 2022 07:24:45 GMT'
}
```
## Environment

nodejs v18.1.0
undici 5.1.1

**Comment by mcollina** [comment]
What are you using for proxy and how is that configured?

**Comment by masx200** [comment]
> What are you using for proxy and how is that configured?

I don't think it has anything to do with the proxy server, because just change `"http://localhost:19001"` to `"http://127.0.0.1:19001"` and it works fine.

**Comment by ronag** [comment]
That sounds more like a node issue than undici issue related to dns resolution.

**Comment by targos** [comment]
This is probably related to the breaking change of Node.js 17 about stopping to reorder the results of `dns.resolve`

**Comment by JiGo2282** [comment]
Please check below issue.

https://github.com/nodejs/undici/issues/1764

**Comment by JiGo2282** [comment]
> It's totally that. On Windows localhost resolves to IPv6.

Please suggest me on below issue.
[
{
"code": 500,
"message": "connect EHOSTUNREACH 172.17.48.1:38249",
"stack": [
"Error: connect EHOSTUNREACH 172.17.48.1:38249",
" at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)"
]
}
]


https://github.com/nodejs/undici/issues/1764

**Comment by treysis** [comment]
That seems unrelated. It's showing an IPv4 address.

**Comment by Jelmerro** [comment]
Is there any solution to using ipv4 for sites that don't work on ipv6? Or just using the ipv4 address with a parameter of sorts? This seems like a major breaking issue to not be able to use ipv4 only sites with undici.

**Comment by treysis** [comment]
Why do the sites have AAAA records if they don't support IPv6?

**Comment by Jelmerro** [comment]
Don't know, I'm not the creator of the sites I can't reach using undici, so I can't fix issues like that. It seems undesirable to have undici fail to connect when a site is miss-configured like that. without an option to force the use of ipv4 in those cases.

**Comment by treysis** [comment]
If a site is misconfigured, a site is misconfigured. If they mess up A records, it won't be reachable for folks on IPv4-only as well.

However, Node v20 comes with Happy Eyeballs support which should mitigate this problem.

**Comment by Jelmerro** [comment]
Just reporting that this also happens for `npm install` and `npx` commands occasionally, this was for `npx http-server`:
```bash
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/http-server failed, reason: connect ECONNREFUSED 2606:4700::6810:1223:443
npm ERR!     at ClientRequest.<anonymous> (/home/jelmerro/.local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!  FetchError: request to https://registry.npmjs.org/http-server failed, reason: connect ECONNREFUSED 2606:4700::6810:1223:443
npm ERR!     at ClientRequest.<anonymous> (/home/jelmerro/.local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '2606:4700::6810:1223',
npm ERR!   port: 443,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by treysis** [comment]
@Jelmerro Do you have IPv6?
