### ISSUE TITLE
Cannot read properties of undefined (reading 'timeoutType')

### ISSUE THREAD

**Issue by emeralddd** [nodejs/undici#1634]
```
/home/obziappdev/wheat/node_modules/undici/lib/client.js:1167
        if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                            ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/home/obziappdev/wheat/node_modules/undici/lib/client.js:1167:29)
    at resume (/home/obziappdev/wheat/node_modules/undici/lib/client.js:1131:3)
    at connect (/home/obziappdev/wheat/node_modules/undici/lib/client.js:1116:3)
```
When i Started my Discordjs bot it caused this

nodejs: 16.17.0

**Comment by ronag** [comment]
What version of undici?

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by elimumford** [comment]
I'm also experiencing this same exception.  

Of note, my scenario is is all TypeScript running as ESM but wrapped in Jest tests, executing through ts-jest... so not uncomplicated... but it does it on any call pattern, including just a simple get through the `fetch` method...

Sorry, this is going to be a shorter just "more info" comment at the moment...

node.js: 18.9.0
undici: 5.10.0
typescript: 4.8.3
jest: 28.1.3
ts-jest: 28.0.8

The underlying error is masked:

```json
{
  "cause": {
    "message": "Cannot destructure property 'exports' of 'undefined' as it is undefined.",
    "stack": "TypeError: Cannot destructure property 'exports' of 'undefined' as it is undefined.\n    at new Parser (/node_modules/undici/lib/client.js:405:34)\n    at connect (/node_modules/undici/lib/client.js:1062:23)"
  },
  "message": "fetch failed",
  "stack": "TypeError: fetch failed\n    at Object.processResponse (/node_modules/undici/lib/fetch/index.js:199:23)\n    at /node_modules/undici/lib/fetch/index.js:928:38\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)"
}
```

This is the `llhttpInstance` variable that is undefined... and it's undefined because the `llhttpPromise` is returning undefined at line 1047 of client.js... which is "fullfilled' by `lazyllhttp`  line 324, but on the first line of the method 325, it checks a JEST_WORKER_ID environment variable and requires `require('./llhttp/llhttp.wasm.js')` which is Web Assembly... and that does something that causes the runtime to do something odd when debugging where it doesn't  advance but returns and have not dug into that...

**Comment by brandsimon** [comment]
I have the same error message (not sure it is the same error).
I am not able to reproduce it, since it happens only randomly after a runtime of 1 to 5 days with a lot of requests. Also I don't know, which dependency exactly causes this call. This error results in a crash of nodejs.

```
node:internal/deps/undici/undici:4240
            if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                                ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (node:internal/deps/undici/undici:4240:33)
    at resume (node:internal/deps/undici/undici:4210:7)
    at connect (node:internal/deps/undici/undici:4199:7)
Thrown at:
    at _resume (node:internal/deps/undici/undici:4240:33)
    at resume (node:internal/deps/undici/undici:4210:7)
    at connect (node:internal/deps/undici/undici:4199:7)

Node.js v18.7.0
```

Please let me know, if I can help somehow. I use nodejs from Debian 12 (Bookworm).

**Comment by anonrig** [comment]
When adding a console.log to catch to line 406:

```
let llhttpPromise = lazyllhttp()
  .catch((error) => {
    console.log('failed to lazy load', error)
  })

```

Here's the full error

```
failed to lazy load ReferenceError: WebAssembly is not defined
    at lazyllhttp (/Users/yagiz/Developer/undici/lib/client.js:352:5)
    at Object.<anonymous> (/Users/yagiz/Developer/undici/lib/client.js:406:21)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1092:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/yagiz/Developer/undici/index.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
```

**Comment by anonrig** [comment]
According to v8 docs, WebAssembly is currently unsupported in `jitless` mode. Referencing: https://v8.dev/blog/jitless

**Comment by nicklaros** [comment]
I don't use `jitless` mode but experiencing this issue as well when running my test using jest 

node 16.15.1

**Comment by KhafraDev** [comment]
This can also be caused by
```
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at lazyllhttp (/home/mzyu2532/test/node_modules/undici/lib/client.js:356:28)
```

**Comment by Dukuu-Wild** [comment]
Same problem for me. But i have:
local win10 installation - works fine.
local android on dori-node - works fine.
cpanel hosting - fails with the discussed error.

Is it connected to any kind of server settings?

**Comment by KhafraDev** [comment]
cpanel (and other browsers in the console) appear to have issues, I'd recommend ssh as an alternative

**Comment by Dukuu-Wild** [comment]
> cpanel (and other consoles in the browser) appear to have issues, I'd recommend ssh as an alternative
i use cpanel's terminal to start an app, and error i see inside of it. Does it change your answer?

**Comment by KhafraDev** [comment]
Nope, try using ssh instead.

**Comment by SimpleCreations** [comment]
To anyone experiencing a similar issue, adding `redirect: 'manual'` to my `fetch` config helped.
Also, the issue is not present in Node 19. Apparently it ships a more recent version of undici where this has been fixed.

The error I was getting was:
```
TypeError: Cannot read properties of undefined (reading 'reason')
      at makeAppropriateNetworkError (node:internal/deps/undici/undici:6736:171)
      at schemeFetch (node:internal/deps/undici/undici:13492:16)
      at node:internal/deps/undici/undici:13422:26
      at mainFetch (node:internal/deps/undici/undici:13439:11)
      at httpRedirectFetch (node:internal/deps/undici/undici:13692:14)
      at httpFetch (node:internal/deps/undici/undici:13638:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async schemeFetch (node:internal/deps/undici/undici:13546:18)
      at async node:internal/deps/undici/undici:13422:20
      at async mainFetch (node:internal/deps/undici/undici:13418:20)
```

**Comment by lmclarke** [comment]
> To anyone experiencing a similar issue, adding `redirect: 'manual'` to my `fetch` config helped. Also, the issue is not present in Node 19. Apparently it ships a more recent version of undici where this has been fixed.
> 
> The error I was getting was:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'reason')
>       at makeAppropriateNetworkError (node:internal/deps/undici/undici:6736:171)
>       at schemeFetch (node:internal/deps/undici/undici:13492:16)
>       at node:internal/deps/undici/undici:13422:26
>       at mainFetch (node:internal/deps/undici/undici:13439:11)
>       at httpRedirectFetch (node:internal/deps/undici/undici:13692:14)
>       at httpFetch (node:internal/deps/undici/undici:13638:28)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async schemeFetch (node:internal/deps/undici/undici:13546:18)
>       at async node:internal/deps/undici/undici:13422:20
>       at async mainFetch (node:internal/deps/undici/undici:13418:20)
> ```

Where is the fetch config?

**Comment by SimpleCreations** [comment]
> Where is the fetch config?

Unfortunately I cannot give the URL I was fetching because it's not public. The rest of the config was default.

**Comment by trivikr** [comment]
Closing as this issue is not present undici fetch shipped in node >=19.x as per last comment.
