### ISSUE TITLE
Unable to `enableNetConnect` for localhost (127.0.0.1)

### ISSUE THREAD

**Issue by paulrobertlloyd** [nodejs/undici#1696]
Opening this as an issue because I think it’s a bug.

### Discussed in https://github.com/nodejs/undici/discussions/1661

<div type='discussions-op-text'>

<sup>Originally posted by **paulrobertlloyd** September 22, 2022</sup>

I’ve set up a mock agent to intercept requests to `https://api.github.com`. However, my program makes calls to the application under test via `127.0.0.1`.

Given I don’t want to mock these requests, I have passed `127.0.0.1` to `enableNetConnect()`, like so:

```js
import { MockAgent, setGlobalDispatcher } from "undici";

const agent = new MockAgent();
agent.disableNetConnect();
agent.enableNetConnect("127.0.0.1");

export const githubAgent = () => {
  const client = agent.get("https://api.github.com");

  client.intercept({
    path: "/repos/user/repo/contents/foo.txt",
    method: "PUT"
  }).reply(201, {
    content: { path: "foo.txt" },
    commit: { message: "Message" },
  }).times(3);

  return client;
};

setGlobalDispatcher(githubAgent());
```

However, when running my tests, all paths are intercepted. For example, I need to call both `http://127.0.0.1:65273/micropub` and `http://127.0.0.1:65273/token` as part of my request chain (the port number is different each time), but the mock agent appears to interpret these as calls as belonging to the same origin in the mock agent, with the following error given:

```
Mock dispatch not matched for path '/micropub': subsequent request to origin https://api.github.com was not allowed (net.connect is not enabled for this origin)
```

<details>
<summary>Full error stack</summary>

```js
TypeError: fetch failed
    at Object.processResponse (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:199:23)
    at /Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:928:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: MockNotMatchedError: Mock dispatch not matched for path '/micropub': subsequent request to origin https://api.github.com was not allowed (net.connect is not enabled for this origin)
      at MockPool.dispatch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/mock/mock-utils.js:362:19)
      at /Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:1906:79
      at new Promise (<anonymous>)
      at dispatch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:1906:12)
      at httpNetworkFetch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:1718:61)
      at httpNetworkOrCacheFetch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:1423:35)
      at httpFetch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:1011:39)
      at schemeFetch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:875:20)
      at /Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:570:22
      at mainFetch (/Users/paulrobertlloyd/Sites/indiekit/node_modules/undici/lib/fetch/index.js:620:7) {
    code: 'UND_MOCK_ERR_MOCK_NOT_MATCHED'
  }
}
```

</details>

</div>

**Comment by KhafraDev** [comment]
if you return `agent` in githubAgent instead of client it will work.

**Comment by paulrobertlloyd** [comment]
@KhafraDev Not sure this is correct, as need to return an agent with the specified intercepts. Anyway, turn out I was able to get this working by using a regex value for `agent.enableNetConnect`:

```js
agent.enableNetConnect(/(?:127\.0\.0\.1:\d{5})/);
```
