### ISSUE TITLE
Error: unknown scheme

### ISSUE THREAD

**Issue by parasop** [nodejs/undici#1720]
cause: Error: unknown scheme
      at makeNetworkError (/workspace/imagine-hydra/node_modules/undici/lib/fetch/response.js:358:9)
      at schemeFetch (/workspace/imagine-hydra/node_modules/undici/lib/fetch/index.js:861:14)
      at /workspace/imagine-hydra/node_modules/undici/lib/fetch/index.js:570:22
      at mainFetch (/workspace/imagine-hydra/node_modules/undici/lib/fetch/index.js:620:7)
      at fetching (/workspace/imagine-hydra/node_modules/undici/lib/fetch/index.js:485:3)
      at Agent.fetch (/workspace/imagine-hydra/node_modules/undici/lib/fetch/index.js:217:16)

**Comment by ZerdoX-x** [comment]
I know this is old but how did you resolve the issue? Do you remember the context of the issue, could you please share any available info you got? I'm currently struggling with same error on sveltekit's SSR side.
