### ISSUE TITLE
Nondescriptive Typeerror: `Cannot read properties of undefined (reading 'reason')`

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/undici#1776]
## Bug Description

Got a strange error using `fetch`, 

```
TypeError: fetch failed
    at fetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/index.js:105:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getLatestVersionOfMajor (/home/runner/work/api/api/scripts/build-container/scripts/update-node.js:48:20)
    at async module.exports (/home/runner/work/api/api/scripts/build-container/scripts/update-node.js:139:22)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13356:16), <anonymous>:4:1)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13452:20) {
  cause: TypeError: Cannot read properties of undefined (reading 'reason')
      at makeAppropriateNetworkError (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/response.js:467:58)
      at schemeFetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:788:12)
      at /home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:605:22
      at mainFetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:655:7)
      at httpRedirectFetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:1230:10)
      at httpFetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:1091:24)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async schemeFetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:889:14)
      at async /home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:605:16
      at async mainFetch (/home/runner/work/api/api/scripts/build-container/node_modules/undici/lib/fetch/index.js:589:16)
}
```

The code is private, but the line that caused this is: ``const response = await fetch(`https://nodejs.org/dist/latest-v${major}.x`);``. I'm investigating now. Most likely an issue on my end but we may be able to benefit from a better error message here.

**Comment by KhafraDev** [comment]
This is an issue in fetch where the controller doesn't have a terminated property (likely got removed a while ago)

https://github.com/nodejs/undici/blob/b041f9a7548d04eb816cdf36690d8f2b6866d25e/lib/fetch/response.js#L439

**Comment by Ethan-Arrowood** [comment]
Hmm okay. I need to crawl the call stack for this then and see why the controller doesn't have a terminated property. It might be a simple `?.` fix too

**Comment by Ethan-Arrowood** [comment]
node-fetch does not have this problem

**Comment by KhafraDev** [comment]
Yeah, it's definitely related to redirects; I couldn't figure out a way to replicate it locally though.

The actual issue is that the connection is being destroyed due to the redirect mode being set to 'follow'. Here's a diff that fixes the issue, but definitely breaks some other things.

```diff
diff --git a/lib/fetch/index.js b/lib/fetch/index.js
index 6c67c1e..2ddbcfd 100644
--- a/lib/fetch/index.js
+++ b/lib/fetch/index.js
@@ -1069,7 +1069,7 @@ async function httpFetch (fetchParams) {
     // encouraged to, transmit an RST_STREAM frame.
     // See, https://github.com/whatwg/fetch/issues/1288
     if (request.redirect !== 'manual') {
-      fetchParams.controller.connection.destroy()
+      // fetchParams.controller.connection.destroy()
     }

     // 2. Switch on request’s redirect mode:
@@ -1562,7 +1562,7 @@ async function httpNetworkFetch (
   includeCredentials = false,
   forceNewConnection = false
 ) {
-  assert(!fetchParams.controller.connection || fetchParams.controller.connection.destroyed)
+  // assert(!fetchParams.controller.connection || fetchParams.controller.connection.destroyed)

   fetchParams.controller.connection = {
     abort: null,
diff --git a/lib/fetch/response.js b/lib/fetch/response.js
index 9c9d628..a991ea0 100644
--- a/lib/fetch/response.js
+++ b/lib/fetch/response.js
@@ -436,7 +436,7 @@ function makeAppropriateNetworkError (fetchParams) {
   // otherwise return a network error.
   return isAborted(fetchParams)
     ? makeNetworkError(new DOMException('The operation was aborted.', 'AbortError'))
-    : makeNetworkError(fetchParams.controller.terminated.reason)
+    : makeNetworkError(new TypeError('request failed'))
 }

 // https://whatpr.org/fetch/1392.html#initialize-a-response
```

**Comment by KhafraDev** [comment]
Actually all the tests pass.

cc @ronag

**Comment by brian6932** [comment]
I have this as well

**Comment by repsac-by** [comment]
@KhafraDev 
> Yeah, it's definitely related to redirects; I couldn't figure out a way to replicate it locally though.

repro:
```js
const { createServer } = require('node:http');
const { fetch } = require('./index');


createServer((req, res) => {
	if (req.url === '/redirect') {
		res.statusCode = 301;
		res.setHeader('location', '/redirect/');
		res.write('<a href="/redirect/">Moved Permanently</a>');
		setTimeout(() => res.end(), 500);
		return;
	}

	res.write(req.url);
	res.end();
}).listen(3000, async () => {
	console.log('listen');

	const resp = await fetch('http://localhost:3000/redirect');
	console.log(await resp.text());
});
```


broken on commit 6883ba5e6ab27eec82dc55eda20438ca50f8e383

**Comment by KhafraDev** [comment]
Thanks! I figured out the reasoning this broke too. We destroy the old connection on redirect, causing the condition in https://github.com/nodejs/undici/commit/6883ba5e6ab27eec82dc55eda20438ca50f8e383 to get triggered. Will post a PR to fix this soon.

**Comment by Vincenius** [comment]
If someone else also stumbles upon this - I had the same error (`Cannot read properties of undefined (reading 'reason')`) on calling a Next.js api endpoint on prod.

The solution for me was to remove the `trailingSlash: true` from the `next.config` file.
