### ISSUE TITLE
Undici fetch timeout should result in `Fetch timeout` error 

### ISSUE THREAD

**Issue by kyrylkov** [nodejs/undici#1922]
Undici fetch timeout should result in `Fetch timeout` error.  Currently it result in `Fetch failed` without any specifics.

Related to https://github.com/nodejs/undici/issues/1373

**Comment by kyrylkov** [comment]
Related to https://github.com/nodejs/undici/issues/1373

**Comment by KhafraDev** [comment]
The error message should stay as it is to match other platforms and make it easier to use/detect. If you want the underlying reason a request failed, you can use error.cause:
```js
import { fetch, Agent } from 'undici'
import { createServer } from 'http'
import { once } from 'events'

const agent = new Agent({
  headersTimeout: 100
})

const server = createServer(() => {}).listen(0)

await once(server, 'listening')

try {
  await fetch(`http://localhost:${server.address().port}`, {
    dispatcher: agent
  })
} catch (e) {
  if (e.message === 'fetch failed') {
    console.log(e.cause)
  }
}
```

which gives us

```
TypeError: fetch failed
   [...]
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (\node_modules\undici\lib\client.js:906:28)
      at Timeout.onTimeout [as _onTimeout] (\node_modules\undici\lib\timers.js:18:13)
      at listOnTimeout (node:internal/timers:568:17)
      at process.processTimers (node:internal/timers:511:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
```
