### ISSUE TITLE
jest errors in CI

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#1945]
See https://github.com/nodejs/undici/actions/runs/4224987179/jobs/7336660766

```
 FAIL  test/jest/interceptor.test.js
  ● Test suite failed to run

    TypeError: \undici\lib\llhttp\constants.js: Cannot read properties of undefined (reading '0')

      345 | }
      346 |
    > 347 | const constants = require('./llhttp/constants')
          |                   ^
      348 | const createRedirectInterceptor = require('./interceptor/redirectInterceptor')
      349 | const EMPTY_BUF = Buffer.alloc(0)
      350 |

      at new SourceMap (node_modules/@babel/generator/src/source-map.ts:61:42)
      at new Generator (node_modules/@babel/generator/src/index.ts:24:35)
      at generate (node_modules/@babel/generator/src/index.ts:271:15)
      at generateCode (node_modules/@babel/core/src/transformation/file/generate.ts:35:22)
      at run (node_modules/@babel/core/src/transformation/index.ts:59:48)
          at run.next (<anonymous>)
      at transform (node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at sync (node_modules/gensync/index.js:89:14)
      at fn (node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:97:14)
      at transformSync (node_modules/@babel/core/src/transform.ts:66:52)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
      at Object.require (lib/client.js:347:19)
      at Object.require (index.js:3:16)
      at Object.require (test/jest/interceptor.test.js:4:28)
```

**Comment by mcollina** [comment]
is this due to the latest security releases?

**Comment by KhafraDev** [comment]
I don't think so, a run yesterday passed without issues (outside of mocha not exiting) https://github.com/nodejs/undici/actions/runs/4219085855/jobs/7324124295

**Comment by mcollina** [comment]
It seems it magically recovered
