### ISSUE TITLE
Body mixin methods missing

### ISSUE THREAD

**Issue by ethanresnick** [nodejs/undici#2010]
## Bug Description

`body.json()` and `body.arrayBuffer()` are missing as functions in the snippet below, even though it seems like the body mixins should be present

## Reproducible By

```
import { fetch } from "undici";

await fetch("https://httpbin.org", {
  method: "POST",
  body: "{}",
  headers: { "Content-Type": "application/json" },
}).then(async (resp) => {
  await resp.body.json();
});

```

## Expected Behavior

JSON parsing should fail, as the body here is an HTML body (for a 405 status code), but the `.json()` method should be defined.

## Logs & Screenshots

```
file:///undici_bug_repro.mjs:9
    await resp.body.json();
                    ^

TypeError: resp.body.json is not a function
    at file:///undici_bug_repro.mjs:9:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///undici_bug_repro.mjs:3:1
```

The same error shown above happens if `resp.body.json()` is replaced with `resp.body.arrayBuffer()`:

```
file:///undici_bug_repro.mjs:9
    await resp.body.arrayBuffer();
                    ^

TypeError: resp.body.arrayBuffer is not a function
    at file:///undici_bug_repro.mjs:9:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///undici_bug_repro.mjs:3:1
```

## Environment

MacOS 13.2
Nodejs 19.6.0
undici 5.21.0

**Comment by KhafraDev** [comment]
The body mixin methods are on the Response object - `response.body` is a Readable web stream. Instead, do `resp.arrayBuffer()` etc.

**Comment by ethanresnick** [comment]
D’oh, of course. Thanks!
