### ISSUE TITLE
Parsers error

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#2011]
Looks like  undici client and/or nodejs server bug.

```
undici.setGlobalDispatcher(
  new undici.Agent({
    connections: 4,
    pipelining: 4,
  })
)

// error
    daemonId: "TYfMxorD6JdV3n"
    fileId: "2101708110007696821.mp4"
    actionId: "TYfN8bRD8xjNyJ"
    action: "access"
    block: {
      "offset": 0,
      "size": 214718819,
      "hash": null,
      "position": 214718819,
      "fileId": "2101708110007696821.mp4",
      "locationId": "N2lMZvi8NQISW_",
      "blockId": "2101708110007696821.mp4"
    }
    locationId: "N2lMZvi8NQISW_"
    blockId: "2101708110007696821.mp4"
    ureq: {
      "method": "GET",
      "url": "http://e339032116dc:8000/file/2101708110007696821.mp4/block/2101708110007696821.mp4",
      "headers": {
        "range": "bytes=0-0"
      }
    }
    err: {
      "type": "HTTPParserError",
      "message": "Expected HTTP/",
      "stack":
          HTTPParserError: Expected HTTP/
              at Parser.execute (/usr/src/app/node_modules/undici/lib/client.js:572:15)
              at Parser.readMore (/usr/src/app/node_modules/undici/lib/client.js:516:12)
              at Socket.onSocketReadable (/usr/src/app/node_modules/undici/lib/client.js:940:10)
              at Socket.emit (node:events:512:28)
              at emitReadable_ (node:internal/streams/readable:590:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
      "name": "HTTPParserError",
      "code": "HPE_INVALID_CONSTANT",
      "data": "\u0000"
    }
    responseTime: 62
```

Need to investigate.

**Comment by Uzlopak** [comment]
I could not reproduce this. Do you have some more information regarding the circumstances?
