### ISSUE TITLE
Get Error in prod no data from file json

### ISSUE THREAD

**Issue by Falter-Sky** [nodejs/undici#2201]
## Bug Description

the nav.json file fails to appear on the website, resulting in missing navigation data.

## Reproducible By
```
export const load = async ({ url, fetch }) => {
    const nav_list = await fetch('/nav.json').then((r) => r.json());
    return {
        nav_title: get_nav_title(url),
        nav_links: nav_list
    };
}
```

## Expected Behavior

my navigation data appears in prod just like in local

## Logs & Screenshots

```
/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:520:23)
    at /var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/util.js:821:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:580:15)
    at successSteps (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:520:23)
    at /var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/util.js:821:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:580:15)
    at successSteps (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:520:23)
    at /var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/util.js:821:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:580:15)
    at successSteps (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:520:23)
    at /var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/util.js:821:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:580:15)
    at successSteps (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:520:23)
    at /var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/util.js:821:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:580:15)
    at successSteps (/var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/body.js:520:23)
    at /var/task/vercel/path0/node_modules/.pnpm/undici@5.22.1/node_modules/undici/lib/fetch/util.js:821:56
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)

```
![example 1](https://github.com/nodejs/undici/assets/85581209/4ac10f25-6228-4737-9e24-34b037fd9ddb)

![example2](https://github.com/nodejs/undici/assets/85581209/1663aa31-764b-4612-9f8d-7e9966d26573)

## Environment

Fedora Linux 38
Node : v18.17.0
pnpm: 8.6.10

### Additional context

still looking for the problem in different areas not sure if this is a undici problem or not, just here to check. :)

**Comment by metcoder95** [comment]
From this line:
`SyntaxError: Unexpected token < in JSON at position 0`

It seems the `nav.json` is not a valid JSON string. Maybe you can start by checking it?

**Comment by Falter-Sky** [comment]
one of the picture the json data not what wrong

**Comment by Falter-Sky** [comment]
I found the the solution!
