### ISSUE TITLE
Lack of `undiciGracefulDispose()`

### ISSUE THREAD

**Issue by loynoir** [nodejs/undici#2206]
## Bug Description

Lack of `undiciGracefulDispose()`.

`deno test` report there are something hold by `undici` not released before text exit.

## Reproducible By

```ts
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";
import { fetch as undiciFetch } from "npm:undici@5.22.1";

describe("reproduce", () => {
  it("reproduce", async () => {
    await undiciFetch("https://unpkg.com");
    console.log("RESP OK");
  });
});
```

```txt
deno test -A --trace-ops ./reproduce.test.ts
running 1 test from ./reproduce.test.ts
reproduce ...
  reproduce ...
------- output -------
RESP OK
----- output end -----
  reproduce ... FAILED (967ms)
reproduce ... FAILED (due to 1 failed step) (975ms)

 ERRORS 

reproduce ... reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:323:15
error: Leaking async ops:
  - 1 async operation to op_read was started in this test, but never completed. The operation was started here:
    at handleOpCallTracing (ext:core/01_core.js:610:42)
    at Object.op_read (ext:core/01_core.js:418:21)
    at TlsConn.read (ext:deno_net/01_net.js:101:26)
    at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:226:50)
    at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:250:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call. The operation was started here:
    at handleOpCallTracing (ext:core/01_core.js:610:42)
    at op_sleep (ext:core/01_core.js:394:21)
    at runAfterTimeout (ext:deno_web/02_timers.js:233:20)
    at initializeTimer (ext:deno_web/02_timers.js:191:3)
    at setTimeout (ext:deno_web/02_timers.js:334:10)
    at Timeout.<computed> (ext:deno_node/internal/timers.mjs:67:7)
    at new Timeout (ext:deno_node/internal/timers.mjs:54:37)
    at setTimeout (node:timers:16:12)
    at refreshTimeout (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/undici/5.22.1/lib/timers.js:46:22)
    at Timeout.refresh (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/undici/5.22.1/lib/timers.js:72:9)

 FAILURES 

reproduce ... reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:323:15

FAILED | 0 passed | 1 failed (1 step) (1s)

error: Test failed
```

## Expected Behavior

```ts
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";
import { fetch as undiciFetch, undiciGracefulDispose } from "npm:undici@5.22.1";

describe("reproduce", () => {
  it("reproduce", async () => {
    await undiciFetch("https://unpkg.com");
    console.log("RESP OK");

    await undiciGracefulDispose();
  });
});
```

```sh
$ deno test -A --trace-ops ./reproduce.test.ts 
Check file:///tmp/reproduce/reproduce.test.ts
running 1 test from ./reproduce.test.ts
reproduce ...
  reproduce ...
------- output -------
RESP OK
----- output end -----
  reproduce ... ok (9ms)
reproduce ... ok (19ms)

ok | 1 passed (1 step) | 0 failed (45ms)
```

**Comment by mcollina** [comment]
Supporting Deno is not a goal at the moment. There is no need for this API for Node.js, so my assumption is that their compatibility layer is missing something.

**Comment by loynoir** [comment]
@mcollina 

Actually, undici fetch function seems works.

```txt
------- output -------
RESP OK
----- output end -----
```

But

```txt
    at setTimeout (node:timers:16:12)
    at refreshTimeout (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/undici/5.22.1/lib/timers.js:46:22)
    at Timeout.refresh (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/undici/5.22.1/lib/timers.js:72:9)
```

https://github.com/nodejs/undici/blob/v5.22.1/lib/timers.js#L46

https://github.com/nodejs/undici/blob/v5.22.1/lib/timers.js#L72


So, I guess below code is missing

```ts
export async function undiciGracefulDispose() {
  clearTimeout(pendingTimeoutIds)
}
```

**Comment by loynoir** [comment]
> There is no need for this API for Node.js

@mcollina 

I guess, the reason is, 

- deno test ensure `timeoutId` life time < test life time

- node test allow `timeoutId` life time > test life time.

**Comment by loynoir** [comment]
> There is no need for this API for Node.js

@mcollina 

I guess, the reason is, 

- deno test ensure `timeoutId` life time < test life time, else error.

- node test allow `timeoutId` life time > test life time.

```ts
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";

describe("reproduce", () => {
  it("reproduce", async () => {
    const id = setTimeout(() => {}, 100);
    void id;
    // clearTimeout(id);
  });
});
```

```txt
Check file:///tmp/reproduce/reproduce.test.ts
running 1 test from ./reproduce.test.ts
reproduce ...
  reproduce ... FAILED (9ms)
reproduce ... FAILED (due to 1 failed step) (17ms)

 ERRORS 

reproduce ... reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:323:15
error: Leaking async ops:
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call.
To get more details where ops were leaked, run again with --trace-ops flag.

 FAILURES 

reproduce ... reproduce => https://deno.land/std@0.196.0/testing/_test_suite.ts:323:15

FAILED | 0 passed | 1 failed (1 step) (39ms)

error: Test failed
```

**Comment by ronag** [comment]
PR is welcome but it's unlikely we will spend time on this.

**Comment by ronag** [comment]
It's not a leak per se, since the timer is `unref`:d.

**Comment by loynoir** [comment]
@ronag Ah, seem not.

**Comment by lucacasonato** [comment]
@ronag `unref`'d timers that are not cleaned up after becoming pointless are still "leaky". They consume resources even if they are unref'd. You should not leak timers...

**Comment by mcollina** [comment]
Timers are cleared, my understanding of this example is that the `fetch()` request is left with lingering data and "used" socket, waiting to be consumed. There is no "hook" to actually clear timers or close the connection, minus waiting for the response to go out of scope and wait for the FinalizationRegistry or timeout to kick in and clean everything up.

@lucacasonato Have you got some suggestions on how to clean everything up in this case?

**Comment by lucacasonato** [comment]
Oh you are totally right! The OP should call `await resp.body.close()`

**Comment by mcollina** [comment]
I'm not 100% sure that would clean up the underlining connection because of keepalive logic.

However, the same could be done with:

```js
import { getGlobalAgent, fetch } from 'undici

await fetch('...')
getGlobalAgent.destroy() // clean up all connections
```

**Comment by loynoir** [comment]
@lucacasonato @mcollina 

Are there any conclusion how to fix this?

```ts
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";
import { fetch as undiciFetch } from "npm:undici@5.22.1";
// import { fetch as undiciFetch } from "npm:undici@5.26.3";

describe("reproduce", () => {
  it("reproduce", async () => {
    const resp = await undiciFetch("https://unpkg.com");
    await resp.text()
  });
});
```

```txt
error: Leaking async ops:
  - 1 async operation to op_read was started in this test, but never completed.
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call.
To get more details where ops were leaked, run again with --trace-ops flag.
```

By the way, deno 1.37.2 cannot import `undici@5.26.3`.

Uncomment `// import { fetch as undiciFetch } from "npm:undici@5.26.3"` got

```
error: TypeError: fetch failed
    at fetch (file:///home/vscode/.cache/deno/npm/x-registry-yarnpkg-com/undici/5.26.3/index.js:110:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.<anonymous> (file:///tmp/x.ts:7:18)
    at async Function.runTest (https://deno.land/std@0.196.0/testing/_test_suite.ts:358:7)
    at async Function.runTest (https://deno.land/std@0.196.0/testing/_test_suite.ts:346:9)
    at async fn (https://deno.land/std@0.196.0/testing/_test_suite.ts:316:13)
Caused by: AssertionError
    at new AssertionError (ext:deno_node/assertion_error.ts:414:11)
    at toNode (node:assert:44:15)
    at assert (node:assert:61:3)
    at new Parser (file:///home/vscode/.cache/deno/npm/x-registry-yarnpkg-com/undici/5.26.3/lib/client.js:568:5)
    at connect (file:///home/vscode/.cache/deno/npm/x-registry-yarnpkg-com/undici/5.26.3/lib/client.js:1269:25)
```

**Comment by mcollina** [comment]
```
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";
import { fetch as undiciFetch, getGlobalAgent, setGlobalAgent, Agent } from "npm:undici@5.22.1";
// import { fetch as undiciFetch } from "npm:undici@5.26.3";

describe("reproduce", () => {
  it("reproduce", async () => {
    const agent = new Agent()
    setGlobalAgent(agent)
    const resp = await undiciFetch("https://unpkg.com");
    await resp.text()
    await agent.destroy()
  });
});
```

Might do the trick.
