### ISSUE TITLE
DispatchInterceptor with POST request doesn't work

### ISSUE THREAD

**Issue by battall** [nodejs/undici#2209]
## Bug Description

when requesting a post request with a dispatch interceptor and using undici.DecoratorHandler, if it is a post request it gives error 
```bash
/Users/battal/Desktop/files/projects/win-bot/node_modules/undici/index.js:109
      Error.captureStackTrace(err, this)
            ^
TypeError: fetch failed
    at fetch (/Users/battal/Desktop/files/projects/win-bot/node_modules/undici/index.js:109:13) {
  cause: TypeError: this.handler.onBodySent is not a function
      at undiciInterceptorTesto.onBodySent (/Users/battal/Desktop/files/projects/win-bot/node_modules/undici/lib/handler/DecoratorHandler.js:33:25)
      at Request.onBodySent (/Users/battal/Desktop/files/projects/win-bot/node_modules/undici/lib/core/request.js:205:24)
      at AsyncWriter.write (/Users/battal/Desktop/files/projects/win-bot/node_modules/undici/lib/client.js:1714:13)
      at writeIterable (/Users/battal/Desktop/files/projects/win-bot/node_modules/undici/lib/client.js:1637:19)
}
```

## Reproducible By

```typescript
import * as undici from "undici";
import { fetch } from "undici";

const undiciInterceptorHeaders = (dispatch: any) => {
  class undiciInterceptorTesto extends undici.DecoratorHandler {
    onHeaders(statusCode: any, headers: any, resume: any) {
      // @ts-ignore
      return super.onHeaders(statusCode, headers, resume);
    }
  }
  return function InterceptedDispatch(opts: any, handler: any) {
    return dispatch(opts, new undiciInterceptorTesto(handler));
  };
};

let dispatcher = new undici.Agent({
  interceptors: {
    Client: [undiciInterceptorHeaders as unknown as undici.Dispatcher],
  },
});

fetch("https://postman-echo.com/post", {
  method: "POST",
  body: new URLSearchParams("amk=5&asdm=6"),
  dispatcher,
})
  .then((res) => res.json())
  .then((body) => {
    console.log(body);
  });
  ```
## Expected Behavior

it should not throw error

## Environment

Macos Sonoma Beta 4
Node v20.5.0

**Comment by battall** [comment]
after some fiddling, creating a empty onBodySent method on undici.DecoratorHandler makes things work, not sure why.

```typescript
const undiciInterceptorHeaders = (dispatch: any) => {
  class undiciInterceptorTesto extends undici.DecoratorHandler {
    onHeaders(statusCode: any, headers: any, resume: any) {
      // @ts-ignore
      return super.onHeaders(statusCode, headers, resume);
    }
    onBodySent() {} // <---- here
  }
  return function InterceptedDispatch(opts: any, handler: any) {
    return dispatch(opts, new undiciInterceptorTesto(handler));
  };
};
```

**Comment by KhafraDev** [comment]
https://github.com/nodejs/undici/blob/c83b084879fa0bb8e0469d31ec61428ac68160d5/docs/api/Dispatcher.md?plain=1#L214

it would appear as though the docs are wrong
