### ISSUE TITLE
code: 'UND_ERR_HEADERS_TIMEOUT'

### ISSUE THREAD

**Issue by jiapei100** [nodejs/undici#2235]
Always meet the following **ERROR**. My app doesn't even use `undici`, but it looks some packages down there are using `undici`, well, also brought the following **ERROR** .

```console
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at async invokeRequest (myproject/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (myproject/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async handleRequest (myproject/node_modules/next/dist/server/lib/router-server.js:447:24)
    at async requestHandler (myproject/node_modules/next/dist/server/lib/router-server.js:464:13)
    at async Server.<anonymous> (myproject/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (myproject/node_modules/next/dist/compiled/undici/index.js:1:62578)
      at Timeout.onTimeout [as _onTimeout] (myproject/node_modules/next/dist/compiled/undici/index.js:2:269659)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
```

Any suggestions? Solutions? 

Thank you ...

**Comment by metcoder95** [comment]
Hey! I recommend you take a look and how your library is configured as the response did not deliver the headers on time. The problem has nothing to do with `undici` but rather the library you are using, and possibly how is configured.
