### ISSUE TITLE
fetch error loses stack context

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2331]
repro from #2328

without the Error.captureStackTrace in index.js:

```
NODE_V8_COVERAGE='./coverage/tmp' node test.mjs
/var/github/undici/lib/compat/dispatcher-weakref.js:25
    dispatcher.on('disconnect', () => {
               ^

TypeError: dispatcher.on is not a function
    at CompatFinalizer.register (/var/github/undici/lib/compat/dispatcher-weakref.js:25:16)
    at new Request (/var/github/undici/lib/fetch/request.js:391:26)
    at fetch (/var/github/undici/lib/fetch/index.js:136:21)
    at fetch (/var/github/undici/index.js:107:20)
    at file:///var/github/undici/test.mjs:5:7
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async loadESM (node:internal/process/esm_loader:42:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.6.1
```

with:

```
 NODE_V8_COVERAGE='./coverage/tmp' node test.mjs
/var/github/undici/index.js:110
        Error.captureStackTrace(err, this)
              ^

TypeError: dispatcher.on is not a function
    at fetch (/var/github/undici/index.js:110:15)
    at async file:///var/github/undici/test.mjs:5:1

Node.js v20.6.1
```

**Comment by metcoder95** [comment]
Shall we remove the `Error.captureStackTrace` at all?

**Comment by KhafraDev** [comment]
yes probably, although it was added on purpose to show where the error originated from

**Comment by KhafraDev** [comment]
if we remove it the stack trace doesn't contain where fetch was called from, probably not much we can do here?

**Comment by metcoder95** [comment]
It has it, isn't it?
I'm looking at these 5 traces:
```shell
    at CompatFinalizer.register (/var/github/undici/lib/compat/dispatcher-weakref.js:25:16)
    at new Request (/var/github/undici/lib/fetch/request.js:391:26)
    at fetch (/var/github/undici/lib/fetch/index.js:136:21)
    at fetch (/var/github/undici/index.js:107:20)
    at file:///var/github/undici/test.mjs:5:7
```

It is more verbose, sure but at least it won't point directly to the `Error.captureStackTrace` call only. Or do you refer to something else?

**Comment by KhafraDev** [comment]
with this code:

```js
import { fetch } from './index.js'

await fetch('https://a')

```

- removing the Error.captureStackTrace

```
TypeError: fetch failed
    at Object.processResponse (/var/github/undici/lib/fetch/index.js:227:23)
    at /var/github/undici/lib/fetch/index.js:939:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
```

with:

```
TypeError: fetch failed
    at fetch (/var/github/undici/index.js:110:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/github/undici/test.mjs:3:1 {
```

notice that the "with" stack trace includes the file fetch was called from, `test.mjs`, while the without does not.

**Comment by metcoder95** [comment]
Ah, ok now I see; within the `dispatcher` example you shared, the entry point is still there; but not with `fetch`.

Playing a bit, I think we can have a quick workaround, but replacing the `constructor` with `module.exports.fetch` instead of `this`, the stack trace remains the same but removes the pointer to the Error.captureStackTrace(err). i.e.

With `Error.captureStackTrace(err, module.exports.fetch)`
```diff
+node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/users/github/undici/playground.mjs:28:1 {
  cause: Error: getaddrinfo ENOTFOUND a
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'a'
  }
}
```

With `Error.captureStackTrace(err, this)`:

```diff
+/Users/metcoder/Documents/Workspace/MetCoder/Undici_Core/index.js:113
        Error.captureStackTrace(err, this)
              ^

TypeError: fetch failed
    at fetch (/Users/metcoder/Documents/Workspace/MetCoder/Undici_Core/index.js:113:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/metcoder/Documents/Workspace/MetCoder/Undici_Core/playground.mjs:28:1 {
  cause: Error: getaddrinfo ENOTFOUND a
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'a'
  }
}
```

I imagine the execution context and how `fetch` gets managed adds quite a few stacks that move out of the scope of the entry point, the reason for the `captureStackTrace` in the first place. By seeking for the function and only the function, the stack trace gets slightly better; at least points that something failed internally instead of pointing to a `Error.captureStackTrace`; but somehow ended nearby 🤔

**Comment by hanayashiki** [comment]
I think `fetch` is quite commonly used, but erroring in `fetch` is now a pain in the ass

<img width="881" alt="image" src="https://github.com/nodejs/undici/assets/26056783/f90def7c-dcba-49c2-8668-44ea66ba3e51">

There is zero hint about who is fetching.

It's 2024.4 and will this issue get some notice?

**Comment by tamird** [comment]
The original "fix" was in https://github.com/nodejs/undici/pull/1619, where diff was
```diff
-    return fetchImpl.apply(dispatcher, arguments)
+    try {
+      return await fetchImpl.apply(dispatcher, arguments)
+    } catch (err) {
+      Error.captureStackTrace(err, this)
+      throw err
+    }
```
this changes two things:
- `await` is added
- try-catch with `captureStackTrace` is added

Could we revert the second part? That should gives us a stack trace from the broken internals of undici all the way up to user code.

**Comment by mcollina** [comment]
@KhafraDev @metcoder95 was there any progress with thisv

**Comment by metcoder95** [comment]
Not really, I haven't dig deeper after that I showed; once done with the other opened PRs I might be able to revisit this.

Stills open if anyone wants to give it a try 👍

**Comment by KhafraDev** [comment]
> That should gives us a stack trace from the broken internals of undici all the way up to user code.

It does not, the original issue then pops up again.

**Comment by prljav** [comment]
will this ever be resolved? i just encountered this and there is literally no origin of the actual source

**Comment by mcollina** [comment]
I'm 100% lost on the reproduction for this. Can somebody add one?

**Comment by eluchsinger** [comment]
Hi!

we're being hunted by these untraceable. Any news on this?

**Comment by Uzlopak** [comment]
This can only happen if the thrown "error" is `null` or `undefined`

**Comment by Uzlopak** [comment]
Does somebody know if we maybe lose the error in cases like [this](https://github.com/nodejs/undici/blob/761fce9aa842ebb784bd723d7885eaa431152e4c/lib/api/api-stream.js#L205)?

callback gets error passed down in queueMicrotask?

**Comment by MoLow** [comment]
@mcollina I'm not sure if this is the exat same issue or not (if not - Please LMK, Il create another issue), but here is a minimal repro:

```mjs
import { createServer } from 'node:http';
import { once } from 'node:events';
import { it } from 'node:test';

it('should repro',async t => {
  const server = createServer((req, res) => {
    res.statusCode = 503;
    res.end('<Service Unavailable>');
  });
  server.listen(0);
  await once(server, 'listening');
  const port = server.address().port;
  t.signal.addEventListener('abort', () => server.close());

  const res = await fetch(`http://localhost:${port}/test`);
  const json = await res.json();
  console.log({ json }, 'Response body');
});
```

output is:
```

test at a.mjs:6:1
✖ should repro (1022.577209ms)
  SyntaxError: Unexpected token '<', "<Service U"... is not valid JSON
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (node:internal/deps/undici/undici:6433:19)
      at successSteps (node:internal/deps/undici/undici:6414:27)
      at readAllBytes (node:internal/deps/undici/undici:5380:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
```
