### ISSUE TITLE
Unable to catch BodyTimeoutError exception

### ISSUE THREAD

**Issue by System233** [nodejs/undici#2523]
## Bug Description

I have the same problem as #1987, `headersTimeout` and `bodyTimeout` neither stop the request in time nor throw a catchable exception. On the contrary, undici emit an error on the unreachable socket.

```log
node:events:493
      throw er; // Unhandled 'error' event
      ^

BodyTimeoutError: Body Timeout Error
    at Timeout.onParserTimeout [as callback] (/mnt/vdb/node/node_modules/undici/lib/client.js:1052:28)
    at Timeout.onTimeout [as _onTimeout] (/mnt/vdb/node/node_modules/undici/lib/timers.js:20:13)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on BodyReadable instance at:
    at BodyReadable.emit (/mnt/vdb/node/node_modules/undici/lib/api/readable.js:85:18)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UND_ERR_BODY_TIMEOUT'
}

Node.js v21.1.0
```

## Reproducible By

```ts
   // pending=[{host:"IP",port:1234,username?:"user",password?:"pass"}]
   // UndiciProxyAgent=undici.ProxyAgent
    // const PROXY_TEST_URL = 'https://1.1.1.1';
    const select = await Promise.all(
      pending.map(
        (host) =>
          new Promise<boolean>((resolve) => {
            undici
              .request(PROXY_TEST_URL, {
                headersTimeout: 2000,
                bodyTimeout: 2000,

                dispatcher: new UndiciProxyAgent({
                  uri: `http://${host.host}:${host.port}`,
                  token: host.username
                    ? `Basic ${Buffer.from(`${host.username}:${host.password}`).toString('base64')}`
                    : undefined
                })
                  .on('connectionError', (error) => {
                    this.logger.error(`ProxyTestFail: host=${host.host} ${stringify(error)}`);
                    resolve(false);
                  }) //not work
                  .on('error' as any, (error) => {
                    this.logger.error(`ProxyTestFail.error: host=${host.host} ${stringify(error)}`);
                    resolve(false);
                  }) //not work
              })
              .then((resp) => resolve(resp.statusCode == 200))
              .catch(() => resolve(false)); //not work
          })
      )
    );
```

## Expected Behavior

The exception should go to the .catch() handler, but neither .catch(), on('error')/ nor .on('connectionError') can catch the exception.

## Environment

Ubuntu 22.04 LTS
Node.js v21.1.0
 "undici": "^6.0.1"

**Comment by ronag** [comment]
```js
.then((resp) => {
  resp.body.on('error', err => console.error(err))
  resp.body.resume() // always consume or destroy response body
  resolve(resp.statusCode == 200)
})
```

**Comment by System233** [comment]
Thank you for clearing up my confusion.
