### ISSUE TITLE
node v21.6 breaks unit tests

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/undici#2615]
While working on eventsource, the unit tests broke in the ci

```sh
test at test/fetch/response.js:202:11
✖ Readable with ArrayBuffer chunk still throws (2.742972ms)
  'Promise resolution is still pending but the event loop has already resolved'

test at test/fetch/response.js:168:1
✖ constructing a Response with a ReadableStream body (12.147774ms)
  'Promise resolution is still pending but the event loop has already resolved'

test at test/fetch/response.js:222:1
✖ constructing Response with third party Blob body
  'Promise resolution is still pending but the event loop has already resolved'

test at test/fetch/response.js:227:1
✖ constructing Response with third party FormData body
  'Promise resolution is still pending but the event loop has already resolved'

test at test/fetch/response.js:237:1
✖ Issue#2465
  'Promise resolution is still pending but the event loop has already resolved'

test at test/fetch/response.js:243:1
✖ Check the Content-Type of invalid formData
  'Promise resolution is still pending but the event loop has already resolved'
```

**Comment by mcollina** [comment]
The regression was introduced in Node v21.6

**Comment by Uzlopak** [comment]
Closing as 21.6.1 fixed this issue
