### ISSUE TITLE
test\client-request.js is consistently failing

### ISSUE THREAD

**Issue by KhafraDev** [nodejs/undici#2949]
```
 ✖ request dump big (57.33ms)
  AssertionError [ERR_ASSERTION]: Failed
      at res.<computed> [as fail] (D:\a\undici\undici\node_modules\@matteo.collina\tspl\tspl.js:52:35)
      at ServerResponse.<anonymous> (D:\a\undici\undici\test\client-request.js:25:29)
      at ServerResponse.emit (node:events:517:28)
      at socketOnDrain (node:_http_server:758:9)
      at Socket.emit (node:events:517:28)
      at afterWrite (node:internal/streams/writable:495:12)
      at afterWriteTick (node:internal/streams/writable:487:10)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: undefined,
    expected: undefined,
    operator: 'fail'
  }
```

it seems to only be failing on Windows. Probably caused by 825e6e11a134305d124eaf76444299a476eff057 @ronag

**Comment by ronag** [comment]
Hm, I thought those windows failures were something else.
