### ISSUE TITLE
`fetch` may try to use a closed connection

### ISSUE THREAD

**Issue by robhogan** [nodejs/undici#3492]
### Version

v22.6.0

### Platform

```text
Darwin MacBook-Pro-6.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

### Subsystem

http

### What steps will reproduce the bug?

```js
// fetch-test.js
const {createServer} = require('node:http');

const port = 8080;
const url = 'http://localhost:' + port;

const server = createServer((req, res) => res.end()).listen(port, async () => {
  await fetch(url);
  server.closeIdleConnections();

  setImmediate(async () => {
    await fetch(url); // Throws TypeError with cause UND_ERR_SOCKET or ECONNRESET
    server.close();
  });
});
```

### How often does it reproduce? Is there a required condition?

Reproduces consistently for me but the error `cause` varies roughly evenly between `ECONNRESET` and `UND_ERR_SOCKET` (details below)

### What is the expected behavior? Why is that the expected behavior?

`fetch` creates a new connection if there are none open, and the request succeeds.

### What do you see instead?

```
node fetch-test.js
node:internal/deps/undici/undici:13178
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at async Immediate.<anonymous> (/Users/robhogan/workspace/fetch-test.js:11:5) {
  [cause]: SocketError: other side closed
      at Socket.<anonymous> (node:internal/deps/undici/undici:6020:28)
      at Socket.emit (node:events:532:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '::1',
      localPort: 57996,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 338,
      bytesRead: 122
    }
  }
}

Node.js v22.6.0
```

**OR**

```
node fetch-test.js
node:internal/deps/undici/undici:13178
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at async Immediate.<anonymous> (/Users/robhogan/workspace/fetch-test.js:11:5) {
  [cause]: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:218:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

Node.js v22.6.0
```

### Additional information

This seems to be quite sensitive to timing/the event loop in a way I haven't pinned down.
 - The `setImmediate` (or `setTimeout(cb, 0)`) is required to reproduce the issue.
 - Adding another `setImmediate` before the second `fetch` makes it succeed.
 - Adding `{headers:{'Connection': 'close'}}` to the first request succeeds.

**Comment by Uzlopak** [comment]
If I put following line in setImmediate then it works as expected, but other tests fail 

https://github.com/nodejs/undici/blob/69cfd97591c0a1eec563590df862caeed304f1c3/lib/dispatcher/client.js#L292

**Comment by jazelly** [comment]
I don't think this is an undici specific issue, as same thing would happen by using native `http.request` in node with `keepAlive`. 

This seems to be an limitation with `keepAlive` implementation. The second request is assigned to the socket that is about to destroy, as it is not aware of that.

**Comment by jakecastelli** [comment]
To extend @jazelly's point - here is a small repo with `node:http`

```js
// fetch-test.js
import { createServer, request } from "node:http";

const port = 8084;
const url = new URL("http://localhost:" + port);

const server = createServer((req, res) => res.end()).listen(port, async () => {
  function httpRequestPromise(reqOptions) {
    return new Promise((resolve, reject) => {
      const req = request(reqOptions, (res) => {
        console.log(`STATUS: ${res.statusCode}`);
        res.setEncoding("utf8");
        res.on("data", () => {});
        res.on("end", () => {
          resolve();
        });
      });

      req.on("error", (error) => {
        console.error(`Request error: ${error.message}`);
        reject(error);
      });
      req.end();
    });
  }

  await httpRequestPromise({
    headers: {
      // 'Content-Type': 'application/json',
      Connection: "keep-alive",
    },
    hostname: url.hostname,
    port: url.port,
    path: url.pathname,
  });

  server.closeIdleConnections();
  console.log("idle connections should have closed...");

  setImmediate(async () => {
    await httpRequestPromise({
      hostname: url.hostname,
      port: url.port,
      path: url.pathname,
    });
    server.close();
  });
});
```

when run this you should see:

```
idle connections should have closed...
Request error: read ECONNRESET
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:218:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

or 

```
idle connections should have closed...
Request error: socket hang up
node:_http_client:530
    emitErrorEvent(req, new ConnResetException('socket hang up'));
                        ^

Error: socket hang up
    at Socket.socketOnEnd (node:_http_client:530:25)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'ECONNRESET'
}
```

if we have `NODE_DEBUG=net` then we can see:

<Details>

<Summary>
Details
</Summary>

```
NET 39667: setupListenHandle null 8084 4 0 undefined
NET 39667: setupListenHandle: create a handle
NET 39667: bind to ::
NET 39667: createConnection [
  [Object: null prototype] {
    headers: { Connection: 'keep-alive' },
    hostname: 'localhost',
    port: '8084',
    path: null,
    host: 'localhost',
    keepAlive: true,
    scheduling: 'lifo',
    timeout: 5000,
    noDelay: true,
    servername: 'localhost',
    _agentKey: 'localhost:8084:',
    encoding: null,
    keepAliveInitialDelay: 1000
  },
  [Function (anonymous)],
  [Symbol(normalizedArgs)]: true
]
NET 39667: pipe false null
NET 39667: connect: find host localhost
NET 39667: connect: dns options { family: undefined, hints: 1024 }
NET 39667: connect: autodetecting
NET 39667: _read - n 65536 isConnecting? true hasHandle? true
NET 39667: _read wait for connection
NET 39667: connect/multiple: only one address found, switching back to single connection
NET 39667: connect: attempting to connect to 127.0.0.1:8084 (addressType: 4)
NET 39667: afterConnect
NET 39667: _read - n 65536 isConnecting? false hasHandle? true
NET 39667: Socket._handle.readStart
NET 39667: onconnection
NET 39667: _read - n 65536 isConnecting? false hasHandle? true
NET 39667: Socket._handle.readStart
STATUS: 200
NET 39667: _read - n 65536 isConnecting? false hasHandle? true
called: 1
53019
NET 39667: destroy
NET 39667: close
NET 39667: close handle
NET 39667: has server
NET 39667: SERVER _emitCloseIfDrained
NET 39667: SERVER handle? true   connections? 0
idle connections should have closed...
NET 39667: emit close
NET 39667: destroy
NET 39667: close
NET 39667: close handle
Request error: read ECONNRESET
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:218:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

</Details>

Close event was emitted after `closeIdleConnections`

```
NET 39667: SERVER _emitCloseIfDrained
NET 39667: SERVER handle? true   connections? 0
idle connections should have closed...  <------------- this is the console log after closeIdleConnections
NET 39667: emit close
NET 39667: destroy
NET 39667: close
NET 39667: close handle
```

**Comment by KhafraDev** [comment]
@nodejs/http

**Comment by mcollina** [comment]
There are is only one thing to do: __always__ retry the request if the other side is closed. This would mean configuring the `retry` interceptor by default for fetch also for POST etc in case of a network error.

**Comment by neoncube2** [comment]
If this issue isn't specific to undici, is there a better place to file this issue?

**Comment by takefy-dev** [comment]
Hey got the same error i don't know why... is anyone as a a fix?

**Comment by RasmusKard** [comment]
This should be relevant https://github.com/nodejs/node/issues/52649

Fix to reduce likelyhood of the race condition happening is released in V23 https://github.com/nodejs/node/commit/05ad94789916563664acb666a7ac367fd8b2cc8b

**Comment by Hona** [comment]
We ran into this with node 20 in github image, with random e2e flakes of ECONNRESET but after upgrading to node 24 this goes away

**Comment by caseywebdev** [comment]
Seeing this error with undici v8.3.0 and node v26.3.0 but it's specific to http2 connections.

```
SocketError: other side closed
    at TLSSocket.onHttp2SocketEnd (node:internal/deps/undici/undici:8571:26)
    at TLSSocket.emit (node:events:521:24)
    at endReadableNT (node:internal/streams/readable:1744:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
```

The error appears uncatchable in client code. I set `allowH2: false` globally and we're not seeing the issue anymore. So this appears to be resolved for H1 but not H2? it's unclear to me if this is an undici or node root issue.

**Comment by Maher-Reven** [comment]
I ran the reporter's repro unchanged across released versions to see where this stands, and the result is more specific than "fixed": the pass rate tracks the scheduling of idle socket validation, including a regression that was introduced and then fixed again inside the 8.10 line.

## Method

The script from the first post, with only two changes: port `0` instead of `8080` so runs cannot collide, and the second `fetch` result printed rather than thrown. Each row is N fresh processes, one request pair each, on Node 24.19.0 / macOS 26.5.2 / arm64.

## Results

| undici | pass | failures |
| --- | --- | --- |
| 6.19.8 | 0/20 | `ECONNRESET`, some `UND_ERR_SOCKET` |
| 6.21.3 | 0/20 | same |
| 7.0.0 → 7.27.0 | 0/20 each | same |
| 7.27.2 | 0/100 | 96 `ECONNRESET`, 4 `UND_ERR_SOCKET` |
| 7.28.0 | 95/100 | 5 `UND_ERR_SOCKET` |
| 8.0.0 | 96/100 | 4 `UND_ERR_SOCKET` |
| 8.5.0 | 94/100 | 1 `ECONNRESET`, 5 `UND_ERR_SOCKET` |
| 8.6.0 | 93/100 | 7 `UND_ERR_SOCKET` |
| 8.7.0 | 95/100 | 5 `UND_ERR_SOCKET` |
| **8.8.0** | **100/100** | — |
| 8.9.0 | **200/200** | — |
| **8.10.0** | **194/200** | 6 `UND_ERR_SOCKET` |
| 8.10.1 | **200/200** | — |
| 8.10.2 | 100/100 | — |
| 8.11.2 | **300/300** | — |

So: a deterministic failure through 7.27.2, a roughly 5% race from 7.28.0 through 8.7.0, clean at 8.8.0, back to about 3% at 8.10.0, and clean again from 8.10.1.

## The pattern lines up with idle socket validation

Those three transitions sit exactly on the three commits that moved when an idle socket is validated:

| first released in | commit | |
| --- | --- | --- |
| 8.8.0 | [`ecf714f8`](https://github.com/nodejs/undici/commit/ecf714f8) | *run idle socket validation off `setImmediate` instead of `setTimeout`* ([#5499](https://github.com/nodejs/undici/pull/5499)) |
| 8.10.0 | [`c76fe46e`](https://github.com/nodejs/undici/commit/c76fe46e) | *revert idle socket validation to `setTimeout(0)` to prevent stall on idle event loop* ([#5606](https://github.com/nodejs/undici/pull/5606)) |
| 8.10.1 | [`8c9182eb`](https://github.com/nodejs/undici/commit/8c9182eb) | *drop idle-socket timer floor with a ref'd `setImmediate`* ([#5707](https://github.com/nodejs/undici/pull/5707)) |

That is what you would expect from this repro in particular. The second `fetch` is scheduled inside `setImmediate`, so it runs in the check phase — after a validation scheduled with `setImmediate`, but before one scheduled with `setTimeout(0)`. When validation lands in the later phase, the request is handed a socket the server has already closed.

Worth saying plainly: this is a correlation across released versions, not a `git bisect` over commits, and I did not read the validation path closely enough to claim causation. But the 8.10.0 dip is not noise — 8.9.0 and 8.10.1 are 200/200 either side of it, and it is the only one of the three releases in that window that carries the `setTimeout(0)` revert.

## Node's bundled copy

Node 20.20.2 ships undici 6.24.1 and fails 10/10, which is consistent with the table. Node 20 is out of support, and Node 24.19.0 ships 7.29.0, which is past the deterministic failure but still inside the residual-race band rather than the clean one.

## What this does not cover

Single machine, macOS arm64, loopback only. A race this narrow is scheduler-sensitive, so the percentages will move on other hardware even if the ordering does not. I did not test Windows or Linux, HTTP/2, or a proxied agent.

On current undici this looks closable. The reason I am posting the whole table rather than just "cannot reproduce on latest" is the 8.10.0 row — if anything is being backported into that line, the `setTimeout(0)` revert is the thing to keep an eye on.
