### ISSUE TITLE
getting issue while running compodoc in angular project

### ISSUE THREAD

**Issue by akashmakde** [nodejs/undici#3501]
getting issue while running npm run compodoc in angular project
ReadableStream
^

ReferenceError: ReadableStream is not defined
at Object. (D:\3.0ang\my-app\node_modules\undici\lib\web\fetch\response.js:527:3)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
at Module.load (node:internal/modules/cjs/loader:1076:32)
at Function.Module._load (node:internal/modules/cjs/loader:911:12)
at Module.require (node:internal/modules/cjs/loader:1100:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object. (D:\3.0ang\my-app\node_modules\undici\lib\web\fetch\index.js:11:5)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

OS: windows 11, node 16.20.0 angular 15.2.0 compodoc 1.1.19

**Comment by Uzlopak** [comment]
We dont support node 16 anymore. Consider using node 18 or downgrade undici to v5.
