### ISSUE TITLE
Flaky test at `test/interceptors/dns.js`

### ISSUE THREAD

**Issue by ruyadorno** [nodejs/undici#3898]
When running [CITGM](https://github.com/nodejs/citgm) to prepare the latest node22 release I stumbled upon the following error:

```
 test at test/interceptors/dns.js:817:1
  Should set lowest TTL between resolved and option maxTTL (604.890833ms)
   AssertionError [ERR_ASSERTION]: 4 == 3
       at res.<computed> [as equal] (/Users/iojs/tmp/citgm_tmp/d4b30272-eb56-4773-af41-d5c7d9f125bf/undici/node_modules/@matteo.collina/tspl/tspl.js:52:35)
       at TestContext.<anonymous> (/Users/iojs/tmp/citgm_tmp/d4b30272-eb56-4773-af41-d5c7d9f125bf/undici/test/interceptors/dns.js:905:5)
       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
       at async Test.run (node:internal/test_runner/test:935:9)
       at async Test.processPendingSubtests (node:internal/test_runner/test:633:7) {
     generatedMessage: true,
     code: 'ERR_ASSERTION',
     actual: 4,
     expected: 3,
     operator: '=='
   }
```

ref: https://ci.nodejs.org/job/citgm-smoker/3516/nodes=osx11/testReport/junit/(root)/citgm/undici_v7_0_0/

cc @metcoder95

**Comment by ruyadorno** [comment]
Upon inspecting the test code I noticed that this specific test is using a timer, which in my experience is a recipe for flaky tests, so after pinging the Undici Slack channel and getting a confirmation from @metcoder95, I'm reporting it here.
