### ISSUE TITLE
mock error

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#670]
I got these errors while running tests:

```js
test/get-head-body.js 2> 
test/get-head-body.js 2> /Users/ronagy/GitHub/public/undici/lib/mock/mock-client.js:52
test/get-head-body.js 2>   async [kClose] () {
test/get-head-body.js 2>          ^
test/get-head-body.js 2> /Users/ronagy/GitHub/public/undici/lib/mock/mock-client.js:1
test/get-head-body.js 2> TypeError: Class extends value #<Object> is not a constructor or null
test/get-head-body.js 2>     at Object.<anonymous> (/Users/ronagy/GitHub/public/undici/lib/mock/mock-client.js:52:10)
test/get-head-body.js 2>     at Object.Module._compile (/Users/ronagy/GitHub/public/undici/node_modules/source-map-support/source-map-support.js:547:25)
test/get-head-body.js 2>     at Generator.next (<anonymous>)
test/get-head-body.js 2>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
test/headers-as-array.js 2> 
test/headers-as-array.js 2> /Users/ronagy/GitHub/public/undici/lib/mock/mock-client.js:52
test/headers-as-array.js 2>   async [kClose] () {
test/headers-as-array.js 2>          ^
test/headers-as-array.js 2> /Users/ronagy/GitHub/public/undici/lib/mock/mock-client.js:1
test/headers-as-array.js 2> TypeError: Class extends value #<Object> is not a constructor or null
test/headers-as-array.js 2>     at Object.<anonymous> (/Users/ronagy/GitHub/public/undici/lib/mock/mock-client.js:52:10)
test/headers-as-array.js 2>     at Object.Module._compile (/Users/ronagy/GitHub/public/undici/node_modules/source-map-support/source-map-support.js:547:25)
test/headers-as-array.js 2>     at Generator.next (<anonymous>)
test/headers-as-array.js 2>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
```

Not sure what they are? @jonnydgreen

**Comment by jonnydgreen** [comment]
@ronag is this off the main branch?

**Comment by jonnydgreen** [comment]
I just ran the following off the `main` branch and worked okay, here're the steps I took:

```sh
rm -rf node_modules package-lock.json
npm install
npm test
```

Node: `v14.15.4`
Npm: `7.7.4`

Which setup do you have?

**Comment by ronag** [comment]
It's a bug I've introduced somewhere but I just don't understand how/where this could happen.

**Comment by jonnydgreen** [comment]
Yeah same here! Could it be a circular dependency in the exports maybe? I've seen similar errors like that caused by circular dependencies in the past. Is the code available to see if I can replicate on my system as well?

**Comment by ronag** [comment]
No, sorry. it's lost in the commits somewhere now.

**Comment by ronag** [comment]
Not a big issue just wanted to raise awareness.

**Comment by jonnydgreen** [comment]
> No, sorry. it's lost in the commits somewhere now.

No worries!

> Not a big issue just wanted to raise awareness.

Cool, I'll keep an eye out. Let me know if you experience it again - happy to take a closer look
