### ISSUE TITLE
[DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated in Node `12.22.0`

### ISSUE THREAD

**Issue by timsuchanek** [nodejs/undici#702]
## Bug Description

When running `undici@3.3.3` with Node `12.22.0`, we get this warning:
```
(node:3380211) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
    at internalBinding (internal/bootstrap/loaders.js:136:34)
    at process.binding (internal/bootstrap/loaders.js:113:14)
    at Object.<anonymous> (/root/code/prisma/src/node_modules/.pnpm/undici@3.3.3/node_modules/undici/lib/node/http-parser.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/code/prisma/src/node_modules/.pnpm/undici@3.3.3/node_modules/undici/lib/core/client.js:5:20)
```

Is there anything we can do to disable it?
Thanks!

**Comment by ronag** [comment]
This will be fixed in undici 4. I think we’re a week away from release.

**Comment by timsuchanek** [comment]
:+1: That was a fast response! Thanks, that's great to hear!
We now have this issue in all Prisma Client installations with the latest Node 12.
Is there anything we could do in the meantime?

**Comment by ronag** [comment]
I might be able to do another v3 release

**Comment by ronag** [comment]
Please try 3.3.4

**Comment by timsuchanek** [comment]
That fixes it!
Thanks a lot for taking care of this so quickly.
We'll do our next stable release next week Tuesday, so then we can directly roll out this fix.
