### ISSUE TITLE
WebAssembly instance out of memory

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#725]
```
[2021-04-12 11:08:00.287 +0000] ERROR (query): view query error
    err: {
      "type": "RangeError",
      "message": "WebAssembly.Instance(): Out of memory: wasm memory",
      "stack":
          RangeError: WebAssembly.Instance(): Out of memory: wasm memory
              at new Parser (/usr/src/app/node_modules/undici/lib/client.js:409:17)
              at connect (/usr/src/app/node_modules/undici/lib/client.js:1001:18)
              at _resume (/usr/src/app/node_modules/undici/lib/client.js:1134:7)
              at resume (/usr/src/app/node_modules/undici/lib/client.js:1035:3)
              at Client.dispatch (/usr/src/app/node_modules/undici/lib/client.js:294:9)
              at Pool.dispatch (/usr/src/app/node_modules/undici/lib/pool.js:204:30)
              at /usr/src/app/node_modules/@nxtedition/lib/couch.js:255:14
              at new Promise (<anonymous>)
              at request (/usr/src/app/node_modules/@nxtedition/lib/couch.js:254:12)
              at Object.allDocs (/usr/src/app/node_modules/@nxtedition/lib/couch.js:420:23)
    }
```

**Comment by ronag** [comment]
@dnlup Thoughts? Do we need an option to set the memory limit? How do we do that?

**Comment by ronag** [comment]
Started running on our test setups 😄

**Comment by ronag** [comment]
I suspect it's because of large payload body. We should probably have a better error for this?

**Comment by ronag** [comment]
Do we have a memory leak?

**Comment by ronag** [comment]
@dnlup Thoughts? Workarounds? Pool/Re-use instances? Have single instance.

**Comment by dnlup** [comment]
It seems like either:

* a memory leak
* more parsers->wasm instances are created and not cleaned up fast enough
* a V8/chromium issue?

I think it should be possible to set up a maximum limit for the memory:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory#syntax

To understand further I would:

* measure memory consumption and which buffers are retained
* rollback to using a single web assembly instance. I suspect most of the flakiness was due to how we handled buffers (not copying them) than the fact that each parser needed its own instance

**Comment by dnlup** [comment]
Good thing you have a test setup and we are in alpha.

**Comment by dnlup** [comment]
It looks like each wasm instance allocates a predefined amount of memory, I need to do more research about that. I think switching to one instance should be more efficient in that regard.

**Comment by ronag** [comment]
> more parsers->wasm instances are created and not cleaned up fast enough

That sounds like a V8 bug then? The GC should run and free them.
