### ISSUE TITLE
Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#728]
```
      "type": "TypeError",
      "message": "Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer",
      "stack":
          TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
              at Uint8Array.set (<anonymous>)
              at Parser.execute (/usr/src/app/node_modules/undici/lib/client.js:520:21)
              at Socket.onSocketData (/usr/src/app/node_modules/undici/lib/client.js:912:17)
              at Socket.emit (node:events:369:20)
              at addChunk (node:internal/streams/readable:313:12)
              at readableAddChunk (node:internal/streams/readable:288:9)
              at Socket.Readable.push (node:internal/streams/readable:227:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by ronag** [comment]
Not sure how it gets detached?

**Comment by ronag** [comment]
@nodejs/v8 not sure if you can do anything about with so little info, just thought I'd do a FYI ping
