### ISSUE TITLE
`assert(currentParser.headers.length % 2 === 0)` failed

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#737]
```
"type":"AssertionError","message":"The expression evaluated to a falsy value:\n\n  assert(currentParser.headers.length % 2 === 0)\n","stack":"AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert(currentParser.headers.length % 2 === 0)\n\n    at wasm_on_header_field (/usr/src/app/node_modules/undici/lib/client.js:420:7)\n    at <anonymous>:wasm-function[39]:0x771\n    at <anonymous>:wasm-function[55]:0x24ef\n    at <anonymous>:wasm-function[54]:0xc53\n    at llhttp_execute (<anonymous>:wasm-function[20]:0x4b4)\n    at Parser.execute (/usr/src/app/node_modules/undici/lib/client.js:528:32)\n    at Socket.onSocketData (/usr/src/app/node_modules/undici/lib/client.js:912:17)\n    at Socket.emit (node:events:369:20)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)","generatedMessage":true,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="
```

**Comment by ronag** [comment]
We are hitting the following assertion, https://github.com/nodejs/undici/blob/main/lib/client.js#L412, not sure how that is possible?

**Comment by ronag** [comment]
Can there be multiple values for the same field?

**Comment by ronag** [comment]
It seems empty header fields are valid.

**Comment by ronag** [comment]
I'm just not sure how to trigger this... I seem to get `''` header value regardless.

**Comment by ronag** [comment]
Ok, I know how to trigger this now.
