### ISSUE TITLE
Multiple requests to the same endpoint cause an error and the container is restarted

### ISSUE THREAD

**Issue by rbonillajr** [nodejs/undici#756]
## Bug Description

With version 3.3.3 it is reporting this error when making several requests.

```
{"level":30,"time":1614213891203,"pid":28,"hostname":"host removed","msg":"Server listening at http://[::]:8080"}
^[[A^[[A^[[B^[[B{"level":30,"time":1614213926009,"pid":28,"hostname":"host removed","reqId":1,"req":{"method":"GET","url":"/playground","hostname":"10.9.0.26:8080","remoteAddress":"::ffff:10.254.252.71","remotePort":49462},"msg":"incoming request"}
{"level":30,"time":1614213926101,"pid":28,"hostname":"host removed","reqId":1,"res":{"statusCode":200},"responseTime":91.69444751739502,"msg":"request completed"}
{"level":30,"time":1614213926512,"pid":28,"hostname":"host removed","reqId":2,"req":{"method":"GET","url":"/playground/init.js","hostname":"10.9.0.26:8080","remoteAddress":"::ffff:10.254.252.71","remotePort":49462},"msg":"incoming request"}
{"level":30,"time":1614213926513,"pid":28,"hostname":"host removed","reqId":2,"res":{"statusCode":200},"responseTime":1.1579179763793945,"msg":"request completed"}
{"level":30,"time":1614213927824,"pid":28,"hostname":"host removed","reqId":3,"req":{"method":"POST","url":"/graphql","hostname":"10.9.0.26:8080","remoteAddress":"::ffff:10.254.252.71","remotePort":49467},"msg":"incoming request"}
{"level":30,"time":1614213928002,"pid":28,"hostname":"host removed","reqId":3,"res":{"statusCode":200},"responseTime":177.4089002609253,"msg":"request completed"}
{"level":30,"time":1614213945835,"pid":28,"hostname":"host removed","reqId":4,"req":{"method":"POST","url":"/graphql","hostname":"10.9.0.26:8080","remoteAddress":"::ffff:10.254.252.71","remotePort":49482},"msg":"incoming request"}
{"level":30,"time":1614213946595,"pid":28,"hostname":"host removed","reqId":4,"res":{"statusCode":200},"responseTime":760.1512966156006,"msg":"request completed"}
{"level":30,"time":1614213950871,"pid":28,"hostname":"host removed","reqId":5,"req":{"method":"GET","url":"/graphql","hostname":"10.9.0.26:8080","remoteAddress":"::ffff:10.254.252.71","remotePort":49484},"msg":"incoming request"}
{"level":50,"time":1614213952295,"pid":28,"hostname":"host removed","stack":"TypeError: Cannot read property 'upgrade' of undefined\n    at Parser.2 (/root/graphql/node_modules/undici/lib/core/client.js:538:17)","type":"Error","msg":"Cannot read property 'upgrade' of undefined"}
error Command failed with exit code 1.
```
With version v4.0.0-alpha.3 it is reporting this error when several requests are made:

```
2021-04-16T19:06:28.155564736Z {"level":30,"time":1618599988155,"pid":27,"hostname":"dev-health-journey-ms-7c89556df4-58b6g","reqId":"req-1i","req":{"method":"POST","url":"/graphql","hostname":"host removed","remoteAddress":"10.9.0.33","remotePort":57360},"msg":"incoming request"}
2021-04-16T19:06:28.605019372Z {"level":30,"time":1618599988604,"pid":27,"hostname":"dev-health-journey-ms-7c89556df4-58b6g","reqId":"req-1j","req":{"method":"POST","url":"/graphql","hostname":"host removed","remoteAddress":"10.9.0.33","remotePort":56490},"msg":"incoming request"}
2021-04-16T19:06:28.709425552Z {"level":50,"time":1618599988709,"pid":27,"hostname":"dev-health-journey-ms-7c89556df4-58b6g","generatedMessage":true,"code":"ERR_ASSERTION","expected":true,"operator":"==","stack":"AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n assert(request)\n\n at Parser.onHeadersComplete (/root/graphql/node_modules/undici/lib/client.js:653:5)\n at wasm_on_headers_complete (/root/graphql/node_modules/undici/lib/client.js:417:28)\n at <anonymous>:wasm-function[8]:0x34d\n at <anonymous>:wasm-function[35]:0x79f\n at <anonymous>:wasm-function[47]:0x5937\n at <anonymous>:wasm-function[46]:0xbbe\n at llhttp_execute (<anonymous>:wasm-function[12]:0x41f)\n at Parser.execute (/root/graphql/node_modules/undici/lib/client.js:524:32)\n at Socket.onSocketData (/root/graphql/node_modules/undici/lib/client.js:885:10)\n at Socket.emit (node:events:378:20)","type":"Error","msg":"The expression evaluated to a falsy value:\n\n assert(request)\n"}
2021-04-16T19:06:28.711560080Z {"level":50,"time":1618599988711,"pid":27,"hostname":"dev-health-journey-ms-7c89556df4-58b6g","reqId":"req-1i","err":{"type":"GraphQLError","message":"Upload attachment error","stack":"UploadAttachmentError: Upload attachment error\n at DocumentService.uploadReimbursementAttachment (/root/graphql/dist/graphql/services/document/index.js:56:19)\n at processTicksAndRejections (node:internal/process/task_queues:94:5)","locations":[{"line":2,"column":3}],"path":["uploadReimbursementAttachment"],"extensions":{"message":"No se pudo completar la carga del archivo","messageCode":"50001"}},"msg":"Upload attachment error"}
2021-04-16T19:06:28.711924502Z {"level":30,"time":1618599988711,"pid":27,"hostname":"dev-health-journey-ms-7c89556df4-58b6g","reqId":"req-1i","res":{"statusCode":200},"responseTime":556.3380651473999,"msg":"request completed"}
2021-04-16T19:06:28.715811536Z second error, exiting
2021-04-16T19:06:28.719117135Z AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
2021-04-16T19:06:28.719137836Z
2021-04-16T19:06:28.719141137Z assert(currentParser == null)
2021-04-16T19:06:28.719143837Z
2021-04-16T19:06:28.719146137Z at Parser.destroy (/root/graphql/node_modules/undici/lib/client.js:550:5)
2021-04-16T19:06:28.719148637Z at detachSocket (/root/graphql/node_modules/undici/lib/client.js:928:19)
2021-04-16T19:06:28.719151337Z at Socket.onSocketClose (/root/graphql/node_modules/undici/lib/client.js:946:3)
2021-04-16T19:06:28.719155237Z at Socket.emit (node:events:390:22)
2021-04-16T19:06:28.719167738Z at TCP.<anonymous> (node:net:665:12)
2021-04-16T19:06:28.719172538Z at TCP.callbackTrampoline (node:internal/async_hooks:132:14) {
2021-04-16T19:06:28.719176239Z generatedMessage: true,
2021-04-16T19:06:28.719179539Z code: 'ERR_ASSERTION',
2021-04-16T19:06:28.719182739Z actual: false,
2021-04-16T19:06:28.719186139Z expected: true,
2021-04-16T19:06:28.719189639Z operator: '=='
2021-04-16T19:06:28.719192840Z }
2021-04-16T19:06:28.804922296Z error Command failed with exit code 1.
2021-04-16T19:06:28.805118308Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Reproducible By
I'm using mercurios. 

my mutation is:

```
mutation uploadReimbursementAttachment($reimbursementAttachmentInput: ReimbursementAttachmentInput!) {
  uploadReimbursementAttachment(reimbursementAttachmentInput: $reimbursementAttachmentInput){
    id,
    name, 
    path
  }
}
```
reimbursementAttachmentInput is:

```
{
    "reimbursementAttachmentInput": {
    "id": "1cc040bd-eb68-4fac-8d45-11caa369ac3e",
    "policyId": "123456",
    "clientCodeCore" : "0000012349999",
    "name": "medicine-invoice1.jpg",
    "mimeType": "image/jpg",
    "attachments": "base64 string" // => add base64 image
  }
}
```

create task runner with postman with 5 to 10 request

## Environment

alpine image
node v14.16.1

### Additional context

it is my fetch function

```
export const fetch = async (url: string, options: Client.RequestOptions) => {
  const client = new Client(url);
  const response = await client.request(options);
  let data = '';
  for await (const chunk of response.body) {
    data += String(chunk);
  }

  client.close();
  return { ...response, body: data };
};
```

**Comment by ronag** [comment]
That's interesting... however difficult to reproduce... I have no experience with mercurios. Do you think you can create a small project I can clone and run?

**Comment by ronag** [comment]
@rbonillajr  can you try with master?

**Comment by rbonillajr** [comment]
The problem doesn't happen when i run locally. It happens to me only in the k8s pod.

The error comes up when you execute the fetch function (I attach the code)

```
export const fetch = async (url: string, options: Client.RequestOptions) => {
  const client = new Client(url);
  const response = await client.request(options);
  let data = '';
  for await (const chunk of response.body) {
    data += String(chunk);
  }

  client.close();
  return { ...response, body: data };
};
```

**Comment by rbonillajr** [comment]
This is the architecture
![diagram](https://user-images.githubusercontent.com/8268226/115559982-cda7c980-a279-11eb-83a2-744d4978a9e2.png)

**Comment by ronag** [comment]
Did you try with master and do you get the same error then?

**Comment by rbonillajr** [comment]
I did not try with master. I do the test and I comment.

**Comment by rbonillajr** [comment]
I only tested with v3.3.3 and v4.0.0-alpha.3. Both give me error.

**Comment by mcollina** [comment]
This has nothing to do with mercurius. You should be able to create a standalone scriptnto reproduce without them.

Anyway, I recommend you to create a Pool and reuse it in your resolver. It would give you the best perf and not have this problem.

**Comment by rbonillajr** [comment]
Thank you very much for the comment @mcollina 
In the same way, it is good that you have reported this bug as it helps to improve the library.
My code is as in the documentation.

thanks.

**Comment by ronag** [comment]
Does your environment somehow mutate node `Sockets`? What Node version are you running there? The error you are seeing should not be possible.

**Comment by mcollina** [comment]
@ronag I think we have a race condition due to the fact we are calling `client.close()` without a event loop run from when the stream ends.

**Comment by ronag** [comment]
> @ronag I think we have a race condition due to the fact we are calling `client.close()` without a event loop run from when the stream ends.

Not sure I follow.

**Comment by mcollina** [comment]
I'll fix it :).

**Comment by rbonillajr** [comment]
Hi, I'm going to work on it.

**Comment by schwers** [comment]
Wanted to report I'm running into this issue as well, specifically in kubernetes.

This only started happening for us yesterday. We were previously talking to our graphql endpoint over https and out through the open internet. When we changed configuration to talk to the same graphql endpoint, but over a kubernetes intracluster networking. e.g. from `https://gql.reddit.com` -> `http://reddit-service-graphql.svc.cluster.local:9090`. 


As soon as our config change went out we started seeing the error `cannot read property 'upgrade' of undefined` point to https://github.com/nodejs/undici/blob/39eba7190985e0ee41124bb4a60ee8fd12710cb3/lib/core/client.js#L538

I've tried upgrading from 3.3.4 to 3.3.6 but am still encountering the issue

 
We're wrapping undici's global `request` (after configuring it with an Agent). Our code is effectively

```ts

setGlobalAgent(new Agent({ connections: poolMaxConnections }));

const request = (requestSpan, args) => {

  const { body: response, ...result } = await request(...(args as Parameters<typeof request>));

  const text: Promise<string> = new Promise((resolve, reject) => {
    response.setEncoding('utf-8');

    let txt = '';

    response.on('data', chunk => {
      txt += chunk;
    });

    response.on('end', () => {
      requestSpan.end();
      resolve(txt);
    });

    response.on('error', reject);
  });

  const json = async () => {
    return JSON.parse(await text);
  };

  // await text so we call span.end
  await text;

  return {
      ...result,
      text: () => text,
      json,
  };
}

```

**Comment by ronag** [comment]
Have you tried v4? Do you have a full stack trace?

**Comment by schwers** [comment]
Unfortunately I'm not getting a helpful stack trace. Our sentry instance is having an error processing the stack for it, I think it's happening out-of-band from when we're making the request.

I'll try upgrade to v4 today / near-future and report back.

**Comment by rbonillajr** [comment]
hi @ronag @mcollina @schwers
I have tried to reproduce the error but it only happens to me when the pod is deployed in kubernetes.
With version 4 it gives me an error, specify it when I create the bug.

**Comment by ronag** [comment]
> hi @ronag @mcollina @schwers
> I have tried to reproduce the error but it only happens to me when the pod is deployed in kubernetes.
> With version 4 it gives me an error, specify it when I create the bug.

You are getting the same error even with 4.0.0-rc.4?

**Comment by aearly** [comment]
@schwers and I updated to 4.0.0-rc.4 today, and are still getting a similar error:

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(currentParser == null)

    at Parser.destroy (/src/node_modules/undici/lib/client.js:557:5)
    at Socket.onSocketClose (/src/node_modules/undici/lib/client.js:975:17)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at TCP.<anonymous> (net.js:673:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```

The surrounding lines in `client.js` are:

```js
    const request = client[kQueue][client[kRunningIdx]]
    assert(request)

    // TODO: Check for content-length mismatch from server?

    assert(!this.upgrade)
```

I believe the original error is about reading `request.upgrade` with an undefined `request`, so I think we might be just failing sooner  now.

**Comment by ronag** [comment]
@mcollina I'm a little confused as to how it's even possible for that assertion to fail there. Any ideas?

**Comment by ronag** [comment]
Ah, it makes more sense after your edit 😄 .

**Comment by schwers** [comment]
I spoke with some our infrastructure engineers who are looking into our networking stack. We're currently using Kubernetes with [Calico](https://docs.projectcalico.org/about/about-calico) managing cluster networking. Can re-confirm that the error only seems to reproduce when using the calico provided cluster url ( e.g. from https://gql.reddit.com -> http://reddit-service-graphql.svc.cluster.local:9090)

**Comment by schwers** [comment]
I just looked through our logs and also found another potentially related error

```
May 19 08:54:56 
  assert(currentParser == null)
May 19 08:54:56 
    at Parser.destroy (/src/node_modules/undici/lib/client.js:557:5)
    at Socket.onSocketClose (/src/node_modules/undici/lib/client.js:975:17)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at TCP.<anonymous> (net.js:673:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```

https://github.com/nodejs/undici/blob/main/lib/client.js#L557

Someone on our infrastructure & networking side is looking into this as well. In the meantime is there any debugging info / logging that would be useful for me to add to our build that could help?

**Comment by ronag** [comment]
I’ve been a little overloaded. I’ll try to get to this soon.

**Comment by ronag** [comment]
@schwers can you try running with https://github.com/nodejs/undici/pull/817 and also please log `dispatcher.on('disconnect', (origin, targets, err) => console.log(origin, targets, err))`?

**Comment by schwers** [comment]
@ronag sure I can try that out this week, likely Tuesday or Wednesday

**Comment by ronag** [comment]
undici@4.0.0-rc5 contains our latest changes that might help debugging this issue.

**Comment by ronag** [comment]
Ping @schwers

**Comment by aearly** [comment]
We tried rolling this out again, still getting a similar error:

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  assert(request)
    at Parser.onHeadersComplete (/src/node_modules/undici/lib/client.js:716:5)
    at wasm_on_headers_complete (/src/node_modules/undici/lib/client.js:396:28)
    at <anonymous>:wasm-function[8]:0x34d
    at <anonymous>:wasm-function[35]:0x7ef
    at <anonymous>:wasm-function[47]:0x5995
    at <anonymous>:wasm-function[46]:0xc22
    at llhttp_execute (<anonymous>:wasm-function[12]:0x41f)
    at Parser.execute (/src/node_modules/undici/lib/client.js:523:30)
    at Socket.onSocketData (/src/node_modules/undici/lib/client.js:943:10)
    at Socket.emit (events.js:315:20)
```

**Comment by ronag** [comment]
That's a hint. Do you have any logs or anything that could provide us more info on how to repro?

**Comment by aearly** [comment]
Unfortunately, this error only manifests in our prod environment, so it's hard to get low-level data out of.  I'll work with our infra team to see it we can get you a redacted tcpdump or HAR file or similar.

**Comment by ronag** [comment]
@aearly @schwers Please try rc6.

**Comment by aearly** [comment]
Sorry for the delay, vacations and shifting priorities got in the way.

I got a chance to try undici@4.0.0.  We are getting a different error now:

```
HTTPParserError: `on_message_begin` callback error
    at Parser.execute (/src/node_modules/undici/lib/client.js:553:15)
    at Socket.onSocketData (/src/node_modules/undici/lib/client.js:972:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```
The error object has the `code` `HPE_CB_MESSAGE_BEGIN`

**Comment by ronag** [comment]
@aearly Could it be that the server is sending a body that differs from the content-length? That error looks very similar to our [test](https://github.com/nodejs/undici/blob/main/test/issue-810.js#L70) for that.

**Comment by rbonillajr** [comment]
@ronag, now that you mention it. my error is when i send files in base64.

**Comment by fholzer** [comment]
>Could it be that the server is sending a body that differs from the content-length

I don't face this issue, but just reading through the comments this rings a familiar tone. I had an issue like that when a reverse proxy changed the content-encoding (in our case by compressing response body data) but not removing/changing/updating content-length response header. Not sure if this is in any way related to the issue reported here, but might help ppl facing this issue investigate their infrastructure.

**Comment by szmarczak** [comment]
I took a look at this. The first stacktrace we got on [3.3.3](https://github.com/nodejs/undici/blob/v3.3.3/lib/core/client.js#L538) was:

### `[1]`

```
TypeError: Cannot read property 'upgrade' of undefined
	at Parser.2 (/root/graphql/node_modules/undici/lib/core/client.js:538:17)
```

This already tells us something. `of undefined`, not `of null`. If it was `of null` then it would mean there was a request before with that id. So `kRunningIdx` must had been incremented. It could be caused via `onMessageComplete` or `onSocketClose` (`onUpgrade` does as well but I don't think these requests do upgrades).

This means the parser emitted headers after the previous has been completed or after the socket closed.

---

The next error comes from [4.0.0-rc.3](https://github.com/nodejs/undici/blob/v4.0.0-rc.3/lib/client.js#L550):

### `[2]`

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

assert(currentParser == null)

	at Parser.destroy (/root/graphql/node_modules/undici/lib/client.js:550:5)
	at detachSocket (/root/graphql/node_modules/undici/lib/client.js:928:19)
	at Socket.onSocketClose (/root/graphql/node_modules/undici/lib/client.js:946:3)
	at Socket.emit (node:events:390:22)
	at TCP.<anonymous> (node:net:665:12)
	at TCP.callbackTrampoline (node:internal/async_hooks:132:14)
```

This means that `currentParser = null` wasn't called. 

https://github.com/nodejs/undici/blob/677d6f9a5eb64ec0e3c346ebdf98b8b79d2b4913/lib/client.js#L519-L520

could be replaced with

```js
    let ret
    try {
        ret = llhttp.exports.llhttp_execute(this.ptr, currentBufferPtr, data.length)
    } finally {
        currentParser = null
    }
```

and this

https://github.com/nodejs/undici/blob/677d6f9a5eb64ec0e3c346ebdf98b8b79d2b4913/lib/client.js#L544-L545

with this

```js
    try {
        llhttp.exports.llhttp_finish(this.ptr) 
    } finally {
        currentParser = null
    }
```

I guess that `execute` or `finish` called other callbacks that required `currentParser = null` but it wasn't set yet.

---

The next stacktrace comes from [4.0.0-rc4](https://github.com/nodejs/undici/blob/v4.0.0-rc.4/lib/client.js#L677):

### `[3]`

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(request)

    at Parser.onHeadersComplete (/src/node_modules/undici/lib/client.js:677:5)
    at wasm_on_headers_complete (/src/node_modules/undici/lib/client.js:406:28)
    at <anonymous>:wasm-function[8]:0x34d
    at <anonymous>:wasm-function[35]:0x7ef
    at <anonymous>:wasm-function[47]:0x5995
    at <anonymous>:wasm-function[46]:0xc22
    at llhttp_execute (<anonymous>:wasm-function[12]:0x41f)
    at Parser.execute (/src/node_modules/undici/lib/client.js:526:32)
    at Socket.onSocketData (/src/node_modules/undici/lib/client.js:906:10)
    at Socket.emit (events.js:315:20)
```

This is exactly the same as the first stacktrace, with the difference it throws earlier.

---

The next stacktrace is:

### `[4]`

```
  assert(currentParser == null)

    at Parser.destroy (/src/node_modules/undici/lib/client.js:557:5)
    at Socket.onSocketClose (/src/node_modules/undici/lib/client.js:975:17)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at TCP.<anonymous> (net.js:673:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```

Which is exactly the same as the second stacktrace.

---

The next stacktrace comes from [4.0.0-rc5](https://github.com/nodejs/undici/blob/v4.0.0-rc.5/lib/client.js#L716):

### `[5]`

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  assert(request)
    at Parser.onHeadersComplete (/src/node_modules/undici/lib/client.js:716:5)
    at wasm_on_headers_complete (/src/node_modules/undici/lib/client.js:396:28)
    at <anonymous>:wasm-function[8]:0x34d
    at <anonymous>:wasm-function[35]:0x7ef
    at <anonymous>:wasm-function[47]:0x5995
    at <anonymous>:wasm-function[46]:0xc22
    at llhttp_execute (<anonymous>:wasm-function[12]:0x41f)
    at Parser.execute (/src/node_modules/undici/lib/client.js:523:30)
    at Socket.onSocketData (/src/node_modules/undici/lib/client.js:943:10)
    at Socket.emit (events.js:315:20)
```

This is exactly the same as third stacktrace. The difference is that the patches I mentioned were applied. 

---

The next stacktrace comes from [4.0.0](https://github.com/nodejs/undici/blob/v4.0.0/lib/client.js#L553):

### `[6]`

```
HTTPParserError: `on_message_begin` callback error
    at Parser.execute (/src/node_modules/undici/lib/client.js:553:15)
    at Socket.onSocketData (/src/node_modules/undici/lib/client.js:972:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```

This error is caused by:

https://github.com/nodejs/undici/blob/v4.0.0/lib/client.js#L618-L630

This means without the `on_message_begin` function we would encounter the same errors as before.

This means the parser received a new request after the previous request completed or after the socket closed.

### Conclusion

- The parser received a new request after the previous one completed or after the socket closed.

**AND / OR**

- `execute` or `finish` called other callbacks that require `currentParser = null` - `finally` won't help here

**Comment by szmarczak** [comment]
Reproducible via:

```js
const net = require('net');
const undici = require('undici');

const request = async () => {
    try {
        const client = new undici.Client('http://localhost:8080');
        const response = await client.request({
            path: '/',
            method: 'GET'
        });
        let data = '';
        for await (const chunk of response.body) {
        data += String(chunk);
        }
        console.log('done', data.length);
    } catch (error) {
        console.log(error.stack);
    }
};


net.createServer((socket) => {
    setTimeout(() => {
        socket.write(`HTTP/1.1 200 OK
content-length: 0
connection: keep-alive
host: localhost:8080\r\n\r\nHTTP/1.1 200 OK
content-length: 0
connection: keep-alive
host: localhost:8080\r\n\r\n`);
        socket.destroy();
    }, 100);
}).listen(8080, () => {
    request();
});
```

On older versions of `undici` this gives the assertion error :heart:

**Comment by ronag** [comment]
```js
'use strict'

const { test } = require('tap')
const { Client } = require('..')
const net = require('net')

test('https://github.com/nodejs/undici/issues/756', (t) => {
  const server = net.createServer((socket) => {
    socket.write(`HTTP/1.1 200 OK
content-length: 0
connection: keep-alive
host: localhost:${server.address().port}\r\n\r\nHTTP/1.1 200 OK
content-length: 0
connection: keep-alive
host: localhost:${server.address().port}\r\n\r\n`)
  })
  t.teardown(server.close.bind(server))

  server.listen(0, () => {
    const client = new Client(`http://localhost:${server.address().port}`)
    t.teardown(client.close.bind(client))

    client.request({
      path: '/',
      method: 'GET'
    }, (err, response) => {
      console.error(err)
      t.error(err)
      response.body.resume()
        .on('error', (err) => {
          throw err
        })
    })
  })
})

```

**Comment by ronag** [comment]
As far as I can see this would be a problem with the server, i.e. we are getting two responses for one request.

**Comment by szmarczak** [comment]
Correct. Maybe let's create a `DanglingResponseError`?

**Comment by ronag** [comment]
> Correct. Maybe let's create a `DanglingResponseError`?

Yea I guess that wouldn't hurt. But in the case of pipelining this is impossible to detect.

**Comment by ronag** [comment]
I also ended up hitting this:

```js
    err: {
      "type": "HTTPParserError",
      "message": "`on_message_begin` callback error",
      "stack":
          HTTPParserError: `on_message_begin` callback error
              at Parser.execute (/app/migrate/node_modules/@nxtedition/lib/node_modules/undici/lib/client.js:595:15)
              at Parser.readMore (/app/migrate/node_modules/@nxtedition/lib/node_modules/undici/lib/client.js:540:12)
              at Socket.onSocketReadable (/app/migrate/node_modules/@nxtedition/lib/node_modules/undici/lib/client.js:1008:10)
              at Socket.emit (node:events:394:28)
              at emitReadable_ (node:internal/streams/readable:573:12)
              at processTicksAndRejections (node:internal/process/task_queues:82:21)
      "data": "\"HTTP/1.1 400 Bad Request\\r\\nServer: MochiWeb/1.0 (Any of you quaids got a smint?)\\r\\nDate: Wed, 18 Aug 2021 14:51:17 GMT\\r\\nContent-Length: 0\\r\\n\\r\\n\"",
      "name": "HTTPParserError",
      "code": "HPE_CB_MESSAGE_BEGIN"
    }
```
