### ISSUE TITLE
Node 16 requires --report classic

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#800]
Node 16 seems to break tap when not using --report classic. Investigate why and see if there is any issue already traking this on tap.

**Comment by trivikr** [comment]
What's the error you're getting when using tap without using `--report classic` on Node 16?

It doesn't break on my MBP:
```console
$ node -v
v16.1.0

$ ./node_modules/.bin/tap test/*.js --no-coverage
 PASS  test/abort-event-emitter.js 20 OK 140.209ms
 ...
 PASS  test/tls.js 26 OK 982.401ms

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   62 passed, 62 of 62 completed
Asserts:  6200 passed, of 6200
Time:     7s

$ ./node_modules/.bin/tap test/*.js --no-coverage --reporter classic
test/abort-controller.js ............................ 40/40
...
test/validations.js ................................. 10/10
total ........................................... 6177/6177

  6177 passing (6s)

  ok
```

It seems to run less tests, i.e. 6177, tests with `--reporter classic` though.

**Comment by ronag** [comment]
@trivikr 

```
undici$ npm run test

> undici@4.0.0-rc.3 test
> tap test/*.js --no-coverage && jest test/jest/test

Error: Cannot find module './reports/base'
Require stack:
- /Users/ronagy/GitHub/public/undici/node_modules/jackspeak/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at resolveFileName (/Users/ronagy/GitHub/public/undici/node_modules/tap/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/Users/ronagy/GitHub/public/undici/node_modules/tap/node_modules/resolve-from/index.js:31:9)
    at module.exports (/Users/ronagy/GitHub/public/undici/node_modules/tap/node_modules/resolve-from/index.js:34:41)
    at importJSX (/Users/ronagy/GitHub/public/undici/node_modules/tap/node_modules/import-jsx/index.js:20:21)
    at module.exports (/Users/ronagy/GitHub/public/undici/node_modules/tap/node_modules/treport/lib/index.js:13:18)
    at exports.makeReporter (/Users/ronagy/GitHub/public/undici/node_modules/tap/bin/run.js:446:23)
    at runTests (/Users/ronagy/GitHub/public/undici/node_modules/tap/bin/run.js:772:3)
    at mainAsync (/Users/ronagy/GitHub/public/undici/node_modules/tap/bin/run.js:268:5)
    at main (/Users/ronagy/GitHub/public/undici/node_modules/tap/bin/run.js:141:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ronagy/GitHub/public/undici/node_modules/jackspeak/noop.js'
  ]
}
TAP version 13
1..0
# time=2.587ms
undici$ 
```

**Comment by mcollina** [comment]
you should update the dependencies, it does not happen on my box.

**Comment by ronag** [comment]
Clearing node modules and re-install fixed it.
