### ISSUE TITLE
expected /HTTP

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#807]
Just encountered one of these again 😢 

```js
3|storage1  |       "type": "HTTPParserError",
33|storage1  |       "message": "Expected HTTP/",
33|storage1  |       "stack":
33|storage1  |           HTTPParserError: Expected HTTP/
33|storage1  |               at Parser.execute (/Users/ronagy/GitHub/nxtedition/nxt/storage/node_modules/undici/lib/client.js:545:28)
33|storage1  |               at Socket.onSocketData (/Users/ronagy/GitHub/nxtedition/nxt/storage/node_modules/undici/lib/client.js:906:10)
33|storage1  |               at Socket.emit (node:events:376:20)
33|storage1  |               at addChunk (node:internal/streams/readable:311:12)
33|storage1  |               at readableAddChunk (node:internal/streams/readable:286:9)
33|storage1  |               at Socket.Readable.push (node:internal/streams/readable:225:10)
33|storage1  |               at TCP.onStreamRead (node:internal/stream_base_commons:192:23)
33|storage1  |       "data": "\"G@\\u0000\\u001b\\u0000\\u0000�\\r\\u0000\\u0001�\\u0000\\u0000\\u0000\\u0001�\\u0000*�\\u0004������������������������������������������������������������������������������������������������������������������������������������������������������������������������GP\\u0000\\u001b\\u0000\\u0002�\\u0017\\u0000\\u0001�\\u0000\\u0000�\\u0000�\\u0000\\u001b�\\u0000�\\u0000\\u000f�\\u0001�\\u0000/D���������������������������������������������������������������������������������������������������������������������������������������������������������������GA\\u00005\\u0007P\\u0001RS,~\\u0000\\u0000\\u0000\\u0001�\\u0000\\u0000��\\u0005!\\n�8�\\u0000\\u0000\\u0000\\u0001\\t�\\u0000\\u0000\\u0000\\u0001gz\\u0000 ��\\u0002�-�\\u000bP\\u0010\\u0010$\\u0000\\u0000\\u0003\\u0000\\u0004\\u0000\\u0000\\u0003\\u0001�<`ʀ\\u0000\\u0000\\u0000\\u0001h�\\u001f,\\u0000\\u0000\\u0000\\u0001e��\\u0005Pv�y\\u0005Z��\\u0003N�&�\\u0019�6<�'��Md1��\\u0004f\\u0013�;�\\u0017��k�(P�\\u0001i��$=����EO�%�\\u00148Dq��W�ɨ\\\\�W$���HR�\\u0002��؅�\\u0018X�W���\\u0019�B\\u00045�ָ``�Y��G\\u0001\\u0000\\u0016�P��J�-e���3�P�\\u0000�x��EtXZ�1�;\\u0016\\u0011�}E\\u000b�\\u0010�\\b\\u001bJ;�݀�r\\u0000F\\u0000.Ŝ޺�R*/�7��دI�\\t�Ubː6�Z\\u0003\\u0002M���hc٦:\\u0010�\\\"��\\u001fc'�\\u001bT/\\u000bu�ͨ\\u0005�\\u0001r�д06��\\b@��t�3hf�.��4���\\u0013�\\u0002���d8\\f�n\\u0019)jFJ��[]^�^\\u001a|lk]Ql���)��-:�ww�o�c�3[\\u000f�G\\u0001\\u0000\\u00171���9�H0&�;��7\\u0002���\\u000b��%6�Ƣ�E��6�x����\\u001f(y\\u0018���f�_gA7\\u0001@�\\u0019h�8<�z�1�`��ܐ3\\u001f\\\\.��Ӊ�8�,5\\u000b�\\f\\u0002�|\\u00029l+����z��\\u0007r\\u000f߿kV�{�zM56*ر�F��\\u0012�t����\\u0005-�P\\u0010z��\\u0012~�D�\\u0000��t;��v\\u0012v;���:��B`aVl,��[RU��턴ߡG\\u0001\\u0000\\u0018�\\f�\\u001a\\u0000\\t�\\f����\\n\\u0011C\\u001d�EP��O�{`�+�K���\\u000b��<���\\u001e\\u0004�RQ�/-����F��\\u000e��\\u000bJox�����\\u0015��+�\\u0016G���W\\tY��c�3��\\b�VQ4���|��\\\\\\u000e�PHӴ��59\\u0003\\t��r��\\\"�\\u0011;yD���:�4���\\f�#���\\u0018����2̅\\u0017\\u001d`\\u000e_.\\u001c\\u0015�SW{�J�@K��\\u0005ts7��\\u0007�{^���9���\\u001dG\\u0001\\u0000\\u0019���aa�T\\r��ǔ\\u000b�(|��\\u001cZ}��\\u0016���oͮ�s\\r;\\u0005�V�cgM�.\\n���u�Z\\u000eh���� �������t��\\u0011ԑȭ�^t\\u0001U��H�\\u001d:iA���\\u000f����\\u0007D��\\u000b��WD�\\u001e�s\\u0006�/�Яl˴G�f97ಏ�\\u000bo�Q�6�A�E�@����6h\\r����V\\u0004�k��A1ᴐ\\u000bx���\\rv\\u0002� ��\\u0004�\\u0012��U\\u0011��[GTG\\u0001\\u0000\\u001a�S��/�c\\t\\u0014�d���$��T\\u001b\\bb�����rAΰ��՚� ߵ��J~EM���{���}\\u0000f�d+�\\u0015���SY�3�.���t����\\u0016\\u001e��\\u0017\\u0012�@9a�[��\\u001e<7\\u001c����}\\f�1�\\u0001-{\\u001c͆�\\f\\u0000\\u0003�)P\\u0005�o-`�U�r����ҹ\\u0000��/%iWY�7b=��v���G\\u001bs���8}�#�W5�\\u0002��p��\\u0004��\\u0011�z��%�y^SG\\u0001\\u0000\\u001b�%\\u001f�á|�=�|\\n[\\f��T�P>M�K!\\u0004wns�y�ú�4�m�ze\\u000b����P�Ҵ��X�,\\r��\\u001c��\\u0017\\u0002����\\u0018�\\u0002�\\u000e�G�\\u0010e����o�<G�\\u0001�$`5]\\u0004M���奉V��\\\\�]���\\u0011u���b�T�.���G8�W\\u0002�ME�}W�3�l�y\\b\\u001a\\u0012\\u0005nr�\\u001a�\\u001f\\u0011\\\"<:��d�ɓ���_���������Q��)�QH�G\\u0001\\u0000\\u001c&e�?J�\\u0006؄��e�\\u00046?��\\u0006\\u000b\\u001c}\\u001d�h\\u0017\\u0019~\\u001f���<�\\u0000�S!�~@-��Pk�f�X�2�\\t>Ĉп\\u0007�Qf�%�H���\\u001eo�_�\\u0003��\\u0018�\\\"�\\u001e\\u000e���h�0@;�\\nCIX�F���~��98�t���T4��\\u0018�Z:�\\u001cIϸY�,��\\u000b59q�P\\u001e\\u0004V����\\r�~��B!����\\\"�q��F��d\\u000f$���\\u0007\\u0016�Z'��E�:�\\\"\\u0005G\\u0001\\u0000\\u001d\\u0017�\\u0013;\\f��\\u00106���7�P��O�*¬\\u0002�-�y���(\\n��cD꾙Ԅ�\\u001d���C��{<xSМ�\\u001e\\u0015\\u0017�fGbV^��E��\\u0014C��\\u0014�\\\"v��o�P\\u0012vrdD�\\u0019�\\u0017۽��\\u0010\\u0011���X\\u0019��8WB+�\\\\\\u0012&���n�b�\\u0002�)�\\u0002�fF#�q���� ��OЎ���Q���XF<�\\u001c��^\\r�}�Hŷ�|!��Td�7�����d�|G\\u0001\\u0000\\u001eV%�i����G��|Z���{~q�\\n��_H\\u0004 \\u0018�ߥ�BPx�/�~���`��\\u001b+��:\\u0004�DO��\\u0000�T��}!�2�q1�\\t��\\u0010�X�4n\\\\���*�f�܋=���i\\\\F��Y?.��|���KP`�]\\nI�i1�vG\\u001f\\u0000%@ŋ�t\\u0003�YN\\u0019D�4W����玺]r%SC�x�������\\u001a4L���C:!7��sg�׭���L3�&G\\u0001\\u0000\\u001f�>/�\\\"��_K��~��W�u�~�4�z^�(���\\u001c�Xxq%�B�\\u0016��/gH\\t[\\u0015��pKI\\u000e\\u001b��6I_���\\u0010�Q=�ꄻ�����:��\\b�m\\u0016�<~-.\\u0019�4�\\u0005�%��b�\\u001d0�x�~c\\r���\\u0018�e\\u000e��7\\u0005���H\\rlP\\u0011�Y�\\u000e�<\\u000e@�-,i!�\\rn2��[�a�/\\u001aV\\u001c��:
```

**Comment by ronag** [comment]
We should probably also keep a reference to the previous buffer and include that in `data`.

**Comment by ronag** [comment]
Or some other information so we can figure out what's going on.... rc.4

**Comment by ronag** [comment]
@indutny what should we include in errors like these to make it easier to debug?

**Comment by szmarczak** [comment]
I wonder if this can occur due to content-length mismatch...

**Comment by indutny** [comment]
I think it is not unlikely that this is due to content-length. llhttp provides `error_pos` that sometimes could help clarify where the parsing error actually occurred, but with this particular error it is just likely that llhttp thinks that the request ended prematurely.

**Comment by ronag** [comment]
Not sure if related https://github.com/nodejs/undici/issues/810.

I haven't been able to create a repro for this. 

> I think it is not unlikely that this is due to content-length. 

@indutny Is there a way to have llhttp protect against this? I suspect something happens where the body doesn't match the content-length, either by being too small or too large and that somehow messes up the llhttp parser state?

**Comment by indutny** [comment]
This isn't just about llhttp when content-length doesn't match the body length - all HTTP parsers should produce errors or fail. The protocol mandates that bytes in the body must be treated as they are and not as a part of the request or response. I'm not sure llhttp can do anything about it unless it was llhttp who didn't parse content-length correctly in the first place.
