### ISSUE TITLE
UND_ERR_TRAILER_MISMATCH

### ISSUE THREAD

**Issue by RuralDependencies** [nodejs/undici#880]
Hello all

https://pinterest.com/ leads to:

[ERROR] TrailerMismatchError: Trailers does not match trailer header
    at wasm_on_message_complete (/home/test/node_modules/undici/lib/client.js:410:28)
    at <anonymous>:wasm-function[37]:0x83b
    at <anonymous>:wasm-function[48]:0x1971
    at <anonymous>:wasm-function[47]:0xc3f
    at llhttp_execute (<anonymous>:wasm-function[13]:0x43c)
    at Parser.execute (/home/test/node_modules/undici/lib/client.js:528:30)
    at TLSSocket.onSocketData (/home/test/node_modules/undici/lib/client.js:972:10)
    at TLSSocket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12) {
  code: 'UND_ERR_TRAILER_MISMATCH'

I'm unsure on how to solve this issue. 
Thank you

**Comment by mcollina** [comment]
Could you please include a full script to reproduce?

**Comment by RuralDependencies** [comment]
It's solved, the IP address was invalid
